-- 0019_naia_programs.sql
-- Seed NAIA baseball programs (2026-27) into the schools reference
-- table, tagged with level NAIA and their conference, so a coach who
-- picks their school gets the level + conference pre-filled (editable).
-- Also seeds the NAIA conferences. Generated from the uploaded sheet.

alter table public.schools add column if not exists division text;
alter table public.schools add column if not exists conference text;

insert into public.schools (name, city, state, division, conference) values
  ('Central Baptist College', 'Conway', 'AR', 'NAIA', 'American Midwest Conference'),
  ('Columbia College', 'Columbia', 'MO', 'NAIA', 'American Midwest Conference'),
  ('Crowley''s Ridge College', 'Paragould', 'AR', 'NAIA', 'American Midwest Conference'),
  ('Hannibal-LaGrange University', 'Hannibal', 'MO', 'NAIA', 'American Midwest Conference'),
  ('Harris-Stowe State University', 'St. Louis', 'MO', 'NAIA', 'American Midwest Conference'),
  ('Mission University', 'Springfield', 'MO', 'NAIA', 'American Midwest Conference'),
  ('University of Health Sciences and Pharmacy in St. Louis', 'St. Louis', 'MO', 'NAIA', 'American Midwest Conference'),
  ('Williams Baptist University', 'Walnut Ridge', 'AR', 'NAIA', 'American Midwest Conference'),
  ('Bluefield University', 'Bluefield', 'VA', 'NAIA', 'Appalachian Athletic Conference'),
  ('Bryan College', 'Dayton', 'TN', 'NAIA', 'Appalachian Athletic Conference'),
  ('Columbia International University', 'Columbia', 'SC', 'NAIA', 'Appalachian Athletic Conference'),
  ('Johnson University', 'Knoxville', 'TN', 'NAIA', 'Appalachian Athletic Conference'),
  ('Milligan University', 'Milligan', 'TN', 'NAIA', 'Appalachian Athletic Conference'),
  ('Montreat College', 'Montreat', 'NC', 'NAIA', 'Appalachian Athletic Conference'),
  ('Reinhardt University', 'Waleska', 'GA', 'NAIA', 'Appalachian Athletic Conference'),
  ('Spartanburg Methodist College', 'Spartanburg', 'SC', 'NAIA', 'Appalachian Athletic Conference'),
  ('Tennessee Wesleyan University', 'Athens', 'TN', 'NAIA', 'Appalachian Athletic Conference'),
  ('Truett McConnell University', 'Cleveland', 'GA', 'NAIA', 'Appalachian Athletic Conference'),
  ('Union Commonwealth University', 'Barbourville', 'KY', 'NAIA', 'Appalachian Athletic Conference'),
  ('University of Pikeville', 'Pikeville', 'KY', 'NAIA', 'Appalachian Athletic Conference'),
  ('Bushnell University', 'Eugene', 'OR', 'NAIA', 'Cascade Collegiate Conference'),
  ('College of Idaho', 'Caldwell', 'ID', 'NAIA', 'Cascade Collegiate Conference'),
  ('Corban University', 'Salem', 'OR', 'NAIA', 'Cascade Collegiate Conference'),
  ('Eastern Oregon University', 'La Grande', 'OR', 'NAIA', 'Cascade Collegiate Conference'),
  ('Lewis-Clark State College', 'Lewiston', 'ID', 'NAIA', 'Cascade Collegiate Conference'),
  ('Oregon Institute of Technology', 'Klamath Falls', 'OR', 'NAIA', 'Cascade Collegiate Conference'),
  ('University of British Columbia', 'Vancouver', 'BC', 'NAIA', 'Cascade Collegiate Conference'),
  ('Warner Pacific University', 'Portland', 'OR', 'NAIA', 'Cascade Collegiate Conference'),
  ('Calumet College of St. Joseph', 'Whiting', 'IN', 'NAIA', 'Chicagoland Collegiate Athletic Conference'),
  ('Indiana University South Bend', 'South Bend', 'IN', 'NAIA', 'Chicagoland Collegiate Athletic Conference'),
  ('Judson University', 'Elgin', 'IL', 'NAIA', 'Chicagoland Collegiate Athletic Conference'),
  ('Olivet Nazarene University', 'Bourbonnais', 'IL', 'NAIA', 'Chicagoland Collegiate Athletic Conference'),
  ('Saint Xavier University', 'Chicago', 'IL', 'NAIA', 'Chicagoland Collegiate Athletic Conference'),
  ('Trinity Christian College', 'Palos Heights', 'IL', 'NAIA', 'Chicagoland Collegiate Athletic Conference'),
  ('University of St. Francis', 'Joliet', 'IL', 'NAIA', 'Chicagoland Collegiate Athletic Conference'),
  ('Viterbo University', 'La Crosse', 'WI', 'NAIA', 'Chicagoland Collegiate Athletic Conference'),
  ('Arkansas Baptist College', 'Little Rock', 'AR', 'NAIA', 'Continental Athletic Conference'),
  ('Carolina University', 'Winston-Salem', 'NC', 'NAIA', 'Continental Athletic Conference'),
  ('Champion Christian College', 'Hot Springs', 'AR', 'NAIA', 'Continental Athletic Conference'),
  ('Fisher College', 'Boston', 'MA', 'NAIA', 'Continental Athletic Conference'),
  ('Florida National University', 'Hialeah', 'FL', 'NAIA', 'Continental Athletic Conference'),
  ('Georgia Gwinnett College', 'Lawrenceville', 'GA', 'NAIA', 'Continental Athletic Conference'),
  ('Georgia Southern University - East Georgia Campus', 'Swainsboro', 'GA', 'NAIA', 'Continental Athletic Conference'),
  ('Hesston College', 'Hesston', 'KS', 'NAIA', 'Continental Athletic Conference'),
  ('Morris College', 'Sumter', 'SC', 'NAIA', 'Continental Athletic Conference'),
  ('Simpson University', 'Redding', 'CA', 'NAIA', 'Continental Athletic Conference'),
  ('Westcliff University', 'Irvine', 'CA', 'NAIA', 'Continental Athletic Conference'),
  ('Bethel University', 'Mishawaka', 'IN', 'NAIA', 'Crossroads League'),
  ('Goshen College', 'Goshen', 'IN', 'NAIA', 'Crossroads League'),
  ('Grace College', 'Winona Lake', 'IN', 'NAIA', 'Crossroads League'),
  ('Huntington University', 'Huntington', 'IN', 'NAIA', 'Crossroads League'),
  ('Indiana Wesleyan University', 'Marion', 'IN', 'NAIA', 'Crossroads League'),
  ('Marian University', 'Indianapolis', 'IN', 'NAIA', 'Crossroads League'),
  ('Mount Vernon Nazarene University', 'Mount Vernon', 'OH', 'NAIA', 'Crossroads League'),
  ('Spring Arbor University', 'Spring Arbor', 'MI', 'NAIA', 'Crossroads League'),
  ('Taylor University', 'Upland', 'IN', 'NAIA', 'Crossroads League'),
  ('University of Saint Francis', 'Fort Wayne', 'IN', 'NAIA', 'Crossroads League'),
  ('Bellevue University', 'Bellevue', 'NE', 'NAIA', 'Frontier Conference'),
  ('Bismarck State College', 'Bismarck', 'ND', 'NAIA', 'Frontier Conference'),
  ('Dakota State University', 'Madison', 'SD', 'NAIA', 'Frontier Conference'),
  ('Dickinson State University', 'Dickinson', 'ND', 'NAIA', 'Frontier Conference'),
  ('Mayville State University', 'Mayville', 'ND', 'NAIA', 'Frontier Conference'),
  ('Valley City State University', 'Valley City', 'ND', 'NAIA', 'Frontier Conference'),
  ('Briar Cliff University', 'Sioux City', 'IA', 'NAIA', 'Great Plains Athletic Conference'),
  ('Concordia University Nebraska', 'Seward', 'NE', 'NAIA', 'Great Plains Athletic Conference'),
  ('Dakota Wesleyan University', 'Mitchell', 'SD', 'NAIA', 'Great Plains Athletic Conference'),
  ('Doane University', 'Crete', 'NE', 'NAIA', 'Great Plains Athletic Conference'),
  ('Dordt University', 'Sioux Center', 'IA', 'NAIA', 'Great Plains Athletic Conference'),
  ('Hastings College', 'Hastings', 'NE', 'NAIA', 'Great Plains Athletic Conference'),
  ('Midland University', 'Fremont', 'NE', 'NAIA', 'Great Plains Athletic Conference'),
  ('Morningside University', 'Sioux City', 'IA', 'NAIA', 'Great Plains Athletic Conference'),
  ('Mount Marty University', 'Yankton', 'SD', 'NAIA', 'Great Plains Athletic Conference'),
  ('Northwestern College', 'Orange City', 'IA', 'NAIA', 'Great Plains Athletic Conference'),
  ('Waldorf University', 'Forest City', 'IA', 'NAIA', 'Great Plains Athletic Conference'),
  ('Arizona Christian University', 'Glendale', 'AZ', 'NAIA', 'Great Southwest Athletic Conference'),
  ('Benedictine University at Mesa', 'Mesa', 'AZ', 'NAIA', 'Great Southwest Athletic Conference'),
  ('Embry-Riddle Aeronautical University (Prescott)', 'Prescott', 'AZ', 'NAIA', 'Great Southwest Athletic Conference'),
  ('Hope International University', 'Fullerton', 'CA', 'NAIA', 'Great Southwest Athletic Conference'),
  ('La Sierra University', 'Riverside', 'CA', 'NAIA', 'Great Southwest Athletic Conference'),
  ('Ottawa University Arizona', 'Surprise', 'AZ', 'NAIA', 'Great Southwest Athletic Conference'),
  ('Park University Gilbert', 'Gilbert', 'AZ', 'NAIA', 'Great Southwest Athletic Conference'),
  ('The Master''s University', 'Santa Clarita', 'CA', 'NAIA', 'Great Southwest Athletic Conference'),
  ('Dillard University', 'New Orleans', 'LA', 'NAIA', 'HBCU Athletic Conference'),
  ('Huston-Tillotson University', 'Austin', 'TX', 'NAIA', 'HBCU Athletic Conference'),
  ('Jarvis Christian University', 'Hawkins', 'TX', 'NAIA', 'HBCU Athletic Conference'),
  ('Oakwood University', 'Huntsville', 'AL', 'NAIA', 'HBCU Athletic Conference'),
  ('Philander Smith University', 'Little Rock', 'AR', 'NAIA', 'HBCU Athletic Conference'),
  ('Rust College', 'Holly Springs', 'MS', 'NAIA', 'HBCU Athletic Conference'),
  ('Southern University at New Orleans', 'New Orleans', 'LA', 'NAIA', 'HBCU Athletic Conference'),
  ('Stillman College', 'Tuscaloosa', 'AL', 'NAIA', 'HBCU Athletic Conference'),
  ('Talladega College', 'Talladega', 'AL', 'NAIA', 'HBCU Athletic Conference'),
  ('Tougaloo College', 'Tougaloo', 'MS', 'NAIA', 'HBCU Athletic Conference'),
  ('Voorhees University', 'Denmark', 'SC', 'NAIA', 'HBCU Athletic Conference'),
  ('Wilberforce University', 'Wilberforce', 'OH', 'NAIA', 'HBCU Athletic Conference'),
  ('Wiley University', 'Marshall', 'TX', 'NAIA', 'HBCU Athletic Conference'),
  ('Baker University', 'Baldwin City', 'KS', 'NAIA', 'Heart of America Athletic Conference'),
  ('Benedictine College', 'Atchison', 'KS', 'NAIA', 'Heart of America Athletic Conference'),
  ('Central Methodist University', 'Fayette', 'MO', 'NAIA', 'Heart of America Athletic Conference'),
  ('Clarke University', 'Dubuque', 'IA', 'NAIA', 'Heart of America Athletic Conference'),
  ('Culver-Stockton College', 'Canton', 'MO', 'NAIA', 'Heart of America Athletic Conference'),
  ('Graceland University', 'Lamoni', 'IA', 'NAIA', 'Heart of America Athletic Conference'),
  ('Grand View University', 'Des Moines', 'IA', 'NAIA', 'Heart of America Athletic Conference'),
  ('MidAmerica Nazarene University', 'Olathe', 'KS', 'NAIA', 'Heart of America Athletic Conference'),
  ('Missouri Baptist University', 'St. Louis', 'MO', 'NAIA', 'Heart of America Athletic Conference'),
  ('Missouri Valley College', 'Marshall', 'MO', 'NAIA', 'Heart of America Athletic Conference'),
  ('Mount Mercy University', 'Cedar Rapids', 'IA', 'NAIA', 'Heart of America Athletic Conference'),
  ('Park University', 'Parkville', 'MO', 'NAIA', 'Heart of America Athletic Conference'),
  ('Peru State College', 'Peru', 'NE', 'NAIA', 'Heart of America Athletic Conference'),
  ('St. Ambrose University', 'Davenport', 'IA', 'NAIA', 'Heart of America Athletic Conference'),
  ('William Penn University', 'Oskaloosa', 'IA', 'NAIA', 'Heart of America Athletic Conference'),
  ('William Woods University', 'Fulton', 'MO', 'NAIA', 'Heart of America Athletic Conference'),
  ('Avila University', 'Kansas City', 'MO', 'NAIA', 'Kansas Collegiate Athletic Conference'),
  ('Bethany College', 'Lindsborg', 'KS', 'NAIA', 'Kansas Collegiate Athletic Conference'),
  ('Evangel University', 'Springfield', 'MO', 'NAIA', 'Kansas Collegiate Athletic Conference'),
  ('Friends University', 'Wichita', 'KS', 'NAIA', 'Kansas Collegiate Athletic Conference'),
  ('Kansas Wesleyan University', 'Salina', 'KS', 'NAIA', 'Kansas Collegiate Athletic Conference'),
  ('McPherson College', 'McPherson', 'KS', 'NAIA', 'Kansas Collegiate Athletic Conference'),
  ('Oklahoma Wesleyan University', 'Bartlesville', 'OK', 'NAIA', 'Kansas Collegiate Athletic Conference'),
  ('Ottawa University', 'Ottawa', 'KS', 'NAIA', 'Kansas Collegiate Athletic Conference'),
  ('Southwestern College', 'Winfield', 'KS', 'NAIA', 'Kansas Collegiate Athletic Conference'),
  ('Sterling College', 'Sterling', 'KS', 'NAIA', 'Kansas Collegiate Athletic Conference'),
  ('Tabor College', 'Hillsboro', 'KS', 'NAIA', 'Kansas Collegiate Athletic Conference'),
  ('University of Saint Mary', 'Leavenworth', 'KS', 'NAIA', 'Kansas Collegiate Athletic Conference'),
  ('York University', 'York', 'NE', 'NAIA', 'Kansas Collegiate Athletic Conference'),
  ('Bethel University', 'McKenzie', 'TN', 'NAIA', 'Mid-South Conference'),
  ('Campbellsville University', 'Campbellsville', 'KY', 'NAIA', 'Mid-South Conference'),
  ('Cumberland University', 'Lebanon', 'TN', 'NAIA', 'Mid-South Conference'),
  ('Freed-Hardeman University', 'Henderson', 'TN', 'NAIA', 'Mid-South Conference'),
  ('Georgetown College', 'Georgetown', 'KY', 'NAIA', 'Mid-South Conference'),
  ('Lindsey Wilson University', 'Columbia', 'KY', 'NAIA', 'Mid-South Conference'),
  ('University of the Cumberlands', 'Williamsburg', 'KY', 'NAIA', 'Mid-South Conference'),
  ('Louisiana Christian University', 'Pineville', 'LA', 'NAIA', 'Red River Athletic Conference'),
  ('Louisiana State University Shreveport', 'Shreveport', 'LA', 'NAIA', 'Red River Athletic Conference'),
  ('Louisiana State University of Alexandria', 'Alexandria', 'LA', 'NAIA', 'Red River Athletic Conference'),
  ('Our Lady of the Lake University', 'San Antonio', 'TX', 'NAIA', 'Red River Athletic Conference'),
  ('Texas A&M University-Texarkana', 'Texarkana', 'TX', 'NAIA', 'Red River Athletic Conference'),
  ('Texas A&M University-Victoria', 'Victoria', 'TX', 'NAIA', 'Red River Athletic Conference'),
  ('Texas College', 'Tyler', 'TX', 'NAIA', 'Red River Athletic Conference'),
  ('University of the Southwest', 'Hobbs', 'NM', 'NAIA', 'Red River Athletic Conference'),
  ('Brescia University', 'Owensboro', 'KY', 'NAIA', 'River States Conference'),
  ('Indiana University Columbus', 'Columbus', 'IN', 'NAIA', 'River States Conference'),
  ('Indiana University Kokomo', 'Kokomo', 'IN', 'NAIA', 'River States Conference'),
  ('Indiana University Southeast', 'New Albany', 'IN', 'NAIA', 'River States Conference'),
  ('Kentucky Christian University', 'Grayson', 'KY', 'NAIA', 'River States Conference'),
  ('Midway University', 'Midway', 'KY', 'NAIA', 'River States Conference'),
  ('Oakland City University', 'Oakland City', 'IN', 'NAIA', 'River States Conference'),
  ('Shawnee State University', 'Portsmouth', 'OH', 'NAIA', 'River States Conference'),
  ('University of Rio Grande', 'Rio Grande', 'OH', 'NAIA', 'River States Conference'),
  ('West Virginia University Institute of Technology', 'Beckley', 'WV', 'NAIA', 'River States Conference'),
  ('Central Christian College of Kansas', 'McPherson', 'KS', 'NAIA', 'Sooner Athletic Conference'),
  ('College of the Ozarks', 'Point Lookout', 'MO', 'NAIA', 'Sooner Athletic Conference'),
  ('Mid-America Christian University', 'Oklahoma City', 'OK', 'NAIA', 'Sooner Athletic Conference'),
  ('Nelson University', 'Waxahachie', 'TX', 'NAIA', 'Sooner Athletic Conference'),
  ('Oklahoma City University', 'Oklahoma City', 'OK', 'NAIA', 'Sooner Athletic Conference'),
  ('Oklahoma Panhandle State University', 'Goodwell', 'OK', 'NAIA', 'Sooner Athletic Conference'),
  ('Southwestern Christian University', 'Bethany', 'OK', 'NAIA', 'Sooner Athletic Conference'),
  ('Texas Wesleyan University', 'Fort Worth', 'TX', 'NAIA', 'Sooner Athletic Conference'),
  ('University of Science and Arts of Oklahoma', 'Chickasha', 'OK', 'NAIA', 'Sooner Athletic Conference'),
  ('Wayland Baptist University', 'Plainview', 'TX', 'NAIA', 'Sooner Athletic Conference'),
  ('Abraham Baldwin Agricultural College', 'Tifton', 'GA', 'NAIA', 'Southern States Athletic Conference'),
  ('Andrew College', 'Cuthbert', 'GA', 'NAIA', 'Southern States Athletic Conference'),
  ('Blue Mountain Christian University', 'Blue Mountain', 'MS', 'NAIA', 'Southern States Athletic Conference'),
  ('Brewton-Parker Christian University', 'Mount Vernon', 'GA', 'NAIA', 'Southern States Athletic Conference'),
  ('Faulkner University', 'Montgomery', 'AL', 'NAIA', 'Southern States Athletic Conference'),
  ('Loyola University New Orleans', 'New Orleans', 'LA', 'NAIA', 'Southern States Athletic Conference'),
  ('Point University', 'West Point', 'GA', 'NAIA', 'Southern States Athletic Conference'),
  ('Thomas University', 'Thomasville', 'GA', 'NAIA', 'Southern States Athletic Conference'),
  ('University of Mobile', 'Mobile', 'AL', 'NAIA', 'Southern States Athletic Conference'),
  ('University of Tennessee Southern', 'Pulaski', 'TN', 'NAIA', 'Southern States Athletic Conference'),
  ('William Carey University', 'Hattiesburg', 'MS', 'NAIA', 'Southern States Athletic Conference'),
  ('Xavier University of Louisiana', 'New Orleans', 'LA', 'NAIA', 'Southern States Athletic Conference'),
  ('Ave Maria University', 'Ave Maria', 'FL', 'NAIA', 'The Sun Conference'),
  ('Florida Memorial University', 'Miami Gardens', 'FL', 'NAIA', 'The Sun Conference'),
  ('Keiser University', 'West Palm Beach', 'FL', 'NAIA', 'The Sun Conference'),
  ('New College of Florida', 'Sarasota', 'FL', 'NAIA', 'The Sun Conference'),
  ('Southeastern University', 'Lakeland', 'FL', 'NAIA', 'The Sun Conference'),
  ('St. Thomas University', 'Miami Gardens', 'FL', 'NAIA', 'The Sun Conference'),
  ('Warner University', 'Lake Wales', 'FL', 'NAIA', 'The Sun Conference'),
  ('Webber International University', 'Babson Park', 'FL', 'NAIA', 'The Sun Conference'),
  ('Aquinas College', 'Grand Rapids', 'MI', 'NAIA', 'Wolverine-Hoosier Athletic Conference'),
  ('Cleary University', 'Howell', 'MI', 'NAIA', 'Wolverine-Hoosier Athletic Conference'),
  ('Cornerstone University', 'Grand Rapids', 'MI', 'NAIA', 'Wolverine-Hoosier Athletic Conference'),
  ('Defiance College', 'Defiance', 'OH', 'NAIA', 'Wolverine-Hoosier Athletic Conference'),
  ('Indiana Institute of Technology', 'Fort Wayne', 'IN', 'NAIA', 'Wolverine-Hoosier Athletic Conference'),
  ('Lawrence Technological University', 'Southfield', 'MI', 'NAIA', 'Wolverine-Hoosier Athletic Conference'),
  ('Madonna University', 'Livonia', 'MI', 'NAIA', 'Wolverine-Hoosier Athletic Conference'),
  ('Rochester Christian University', 'Rochester Hills', 'MI', 'NAIA', 'Wolverine-Hoosier Athletic Conference'),
  ('University of Michigan-Dearborn', 'Dearborn', 'MI', 'NAIA', 'Wolverine-Hoosier Athletic Conference'),
  ('University of Northwestern Ohio', 'Lima', 'OH', 'NAIA', 'Wolverine-Hoosier Athletic Conference')
on conflict (name_key, state_key) do update set
  division = excluded.division,
  conference = excluded.conference,
  city = coalesce(excluded.city, public.schools.city);

insert into public.conferences (name, division) values
  ('American Midwest Conference', 'NAIA'),
  ('Appalachian Athletic Conference', 'NAIA'),
  ('Cascade Collegiate Conference', 'NAIA'),
  ('Chicagoland Collegiate Athletic Conference', 'NAIA'),
  ('Continental Athletic Conference', 'NAIA'),
  ('Crossroads League', 'NAIA'),
  ('Frontier Conference', 'NAIA'),
  ('Great Plains Athletic Conference', 'NAIA'),
  ('Great Southwest Athletic Conference', 'NAIA'),
  ('HBCU Athletic Conference', 'NAIA'),
  ('Heart of America Athletic Conference', 'NAIA'),
  ('Kansas Collegiate Athletic Conference', 'NAIA'),
  ('Mid-South Conference', 'NAIA'),
  ('Red River Athletic Conference', 'NAIA'),
  ('River States Conference', 'NAIA'),
  ('Sooner Athletic Conference', 'NAIA'),
  ('Southern States Athletic Conference', 'NAIA'),
  ('The Sun Conference', 'NAIA'),
  ('Wolverine-Hoosier Athletic Conference', 'NAIA')
on conflict (name_key, division) do nothing;
