-- 0021_d2_programs.sql
-- Seed NCAA D2 baseball programs (2026-27) into the schools reference
-- table, tagged with level D2 and their conference, so a coach who
-- picks their school gets the level + conference pre-filled (editable).
-- Also seeds the D2 conferences. Generated from the uploaded sheet.

alter table public.schools add column if not exists division text;
alter table public.schools add column if not exists conference text;

insert into public.schools (name, city, state, division, conference) values
  ('California State Polytechnic University, Pomona', 'Pomona', 'CA', 'D2', 'California Collegiate Athletic Association'),
  ('California State University San Marcos', 'San Marcos', 'CA', 'D2', 'California Collegiate Athletic Association'),
  ('California State University, Chico', 'Chico', 'CA', 'D2', 'California Collegiate Athletic Association'),
  ('California State University, Dominguez Hills', 'Carson', 'CA', 'D2', 'California Collegiate Athletic Association'),
  ('California State University, East Bay', 'Hayward', 'CA', 'D2', 'California Collegiate Athletic Association'),
  ('California State University, Los Angeles', 'Los Angeles', 'CA', 'D2', 'California Collegiate Athletic Association'),
  ('California State University, Monterey Bay', 'Seaside', 'CA', 'D2', 'California Collegiate Athletic Association'),
  ('California State University, San Bernardino', 'San Bernardino', 'CA', 'D2', 'California Collegiate Athletic Association'),
  ('California State University, Stanislaus', 'Turlock', 'CA', 'D2', 'California Collegiate Athletic Association'),
  ('Fresno Pacific University', 'Fresno', 'CA', 'D2', 'California Collegiate Athletic Association'),
  ('Menlo College', 'Atherton', 'CA', 'D2', 'California Collegiate Athletic Association'),
  ('Caldwell University', 'Caldwell', 'NJ', 'D2', 'Central Atlantic Collegiate Conference'),
  ('Chestnut Hill College', 'Philadelphia', 'PA', 'D2', 'Central Atlantic Collegiate Conference'),
  ('Dominican University New York', 'Orangeburg', 'NY', 'D2', 'Central Atlantic Collegiate Conference'),
  ('Felician University', 'Rutherford', 'NJ', 'D2', 'Central Atlantic Collegiate Conference'),
  ('Georgian Court University', 'Lakewood', 'NJ', 'D2', 'Central Atlantic Collegiate Conference'),
  ('Goldey-Beacom College', 'Wilmington', 'DE', 'D2', 'Central Atlantic Collegiate Conference'),
  ('Holy Family University', 'Philadelphia', 'PA', 'D2', 'Central Atlantic Collegiate Conference'),
  ('Lincoln University (PA)', 'Lincoln University', 'PA', 'D2', 'Central Atlantic Collegiate Conference'),
  ('Post University', 'Waterbury', 'CT', 'D2', 'Central Atlantic Collegiate Conference'),
  ('Thomas Jefferson University', 'Philadelphia', 'PA', 'D2', 'Central Atlantic Collegiate Conference'),
  ('University of Bridgeport', 'Bridgeport', 'CT', 'D2', 'Central Atlantic Collegiate Conference'),
  ('Wilmington University', 'New Castle', 'DE', 'D2', 'Central Atlantic Collegiate Conference'),
  ('Barton College', 'Wilson', 'NC', 'D2', 'Conference Carolinas'),
  ('Belmont Abbey College', 'Belmont', 'NC', 'D2', 'Conference Carolinas'),
  ('Chowan University', 'Murfreesboro', 'NC', 'D2', 'Conference Carolinas'),
  ('Emmanuel University', 'Franklin Springs', 'GA', 'D2', 'Conference Carolinas'),
  ('Erskine College', 'Due West', 'SC', 'D2', 'Conference Carolinas'),
  ('Ferrum College', 'Ferrum', 'VA', 'D2', 'Conference Carolinas'),
  ('Francis Marion University', 'Florence', 'SC', 'D2', 'Conference Carolinas'),
  ('King University', 'Bristol', 'TN', 'D2', 'Conference Carolinas'),
  ('North Greenville University', 'Tigerville', 'SC', 'D2', 'Conference Carolinas'),
  ('Shorter University', 'Rome', 'GA', 'D2', 'Conference Carolinas'),
  ('Southern Wesleyan University', 'Central', 'SC', 'D2', 'Conference Carolinas'),
  ('University of Mount Olive', 'Mount Olive', 'NC', 'D2', 'Conference Carolinas'),
  ('University of North Carolina at Pembroke', 'Pembroke', 'NC', 'D2', 'Conference Carolinas'),
  ('Young Harris College', 'Young Harris', 'GA', 'D2', 'Conference Carolinas'),
  ('College of Staten Island (CUNY)', 'Staten Island', 'NY', 'D2', 'East Coast Conference'),
  ('D''Youville University', 'Buffalo', 'NY', 'D2', 'East Coast Conference'),
  ('Mercy University', 'Dobbs Ferry', 'NY', 'D2', 'East Coast Conference'),
  ('Molloy University', 'Rockville Centre', 'NY', 'D2', 'East Coast Conference'),
  ('Queens College (CUNY)', 'Queens', 'NY', 'D2', 'East Coast Conference'),
  ('St. Thomas Aquinas College', 'Sparkill', 'NY', 'D2', 'East Coast Conference'),
  ('Arkansas Tech University', 'Russellville', 'AR', 'D2', 'Great American Conference'),
  ('East Central University', 'Ada', 'OK', 'D2', 'Great American Conference'),
  ('Harding University', 'Searcy', 'AR', 'D2', 'Great American Conference'),
  ('Henderson State University', 'Arkadelphia', 'AR', 'D2', 'Great American Conference'),
  ('Northwestern Oklahoma State University', 'Alva', 'OK', 'D2', 'Great American Conference'),
  ('Oklahoma Baptist University', 'Shawnee', 'OK', 'D2', 'Great American Conference'),
  ('Ouachita Baptist University', 'Arkadelphia', 'AR', 'D2', 'Great American Conference'),
  ('Southeastern Oklahoma State University', 'Durant', 'OK', 'D2', 'Great American Conference'),
  ('Southern Arkansas University', 'Magnolia', 'AR', 'D2', 'Great American Conference'),
  ('Southern Nazarene University', 'Bethany', 'OK', 'D2', 'Great American Conference'),
  ('Southwestern Oklahoma State University', 'Weatherford', 'OK', 'D2', 'Great American Conference'),
  ('University of Arkansas at Monticello', 'Monticello', 'AR', 'D2', 'Great American Conference'),
  ('Davenport University', 'Grand Rapids', 'MI', 'D2', 'Great Lakes Intercollegiate Athletic Conference'),
  ('Grand Valley State University', 'Allendale', 'MI', 'D2', 'Great Lakes Intercollegiate Athletic Conference'),
  ('Purdue University Northwest', 'Hammond', 'IN', 'D2', 'Great Lakes Intercollegiate Athletic Conference'),
  ('Roosevelt University', 'Chicago', 'IL', 'D2', 'Great Lakes Intercollegiate Athletic Conference'),
  ('Saginaw Valley State University', 'University Center', 'MI', 'D2', 'Great Lakes Intercollegiate Athletic Conference'),
  ('University of Wisconsin-Parkside', 'Kenosha', 'WI', 'D2', 'Great Lakes Intercollegiate Athletic Conference'),
  ('Wayne State University', 'Detroit', 'MI', 'D2', 'Great Lakes Intercollegiate Athletic Conference'),
  ('Drury University', 'Springfield', 'MO', 'D2', 'Great Lakes Valley Conference'),
  ('Lewis University', 'Romeoville', 'IL', 'D2', 'Great Lakes Valley Conference'),
  ('Lincoln University (MO)', 'Jefferson City', 'MO', 'D2', 'Great Lakes Valley Conference'),
  ('Maryville University', 'St. Louis', 'MO', 'D2', 'Great Lakes Valley Conference'),
  ('McKendree University', 'Lebanon', 'IL', 'D2', 'Great Lakes Valley Conference'),
  ('Missouri University of Science and Technology', 'Rolla', 'MO', 'D2', 'Great Lakes Valley Conference'),
  ('Quincy University', 'Quincy', 'IL', 'D2', 'Great Lakes Valley Conference'),
  ('Rockhurst University', 'Kansas City', 'MO', 'D2', 'Great Lakes Valley Conference'),
  ('Southwest Baptist University', 'Bolivar', 'MO', 'D2', 'Great Lakes Valley Conference'),
  ('Truman State University', 'Kirksville', 'MO', 'D2', 'Great Lakes Valley Conference'),
  ('University of Illinois Springfield', 'Springfield', 'IL', 'D2', 'Great Lakes Valley Conference'),
  ('University of Indianapolis', 'Indianapolis', 'IN', 'D2', 'Great Lakes Valley Conference'),
  ('University of Missouri-St. Louis', 'St. Louis', 'MO', 'D2', 'Great Lakes Valley Conference'),
  ('Upper Iowa University', 'Fayette', 'IA', 'D2', 'Great Lakes Valley Conference'),
  ('William Jewell College', 'Liberty', 'MO', 'D2', 'Great Lakes Valley Conference'),
  ('Ashland University', 'Ashland', 'OH', 'D2', 'Great Midwest Athletic Conference'),
  ('Cedarville University', 'Cedarville', 'OH', 'D2', 'Great Midwest Athletic Conference'),
  ('Hillsdale College', 'Hillsdale', 'MI', 'D2', 'Great Midwest Athletic Conference'),
  ('Kentucky Wesleyan College', 'Owensboro', 'KY', 'D2', 'Great Midwest Athletic Conference'),
  ('Lake Erie College', 'Painesville', 'OH', 'D2', 'Great Midwest Athletic Conference'),
  ('Malone University', 'Canton', 'OH', 'D2', 'Great Midwest Athletic Conference'),
  ('Northwood University', 'Midland', 'MI', 'D2', 'Great Midwest Athletic Conference'),
  ('Ohio Dominican University', 'Columbus', 'OH', 'D2', 'Great Midwest Athletic Conference'),
  ('Thomas More University', 'Crestview Hills', 'KY', 'D2', 'Great Midwest Athletic Conference'),
  ('Tiffin University', 'Tiffin', 'OH', 'D2', 'Great Midwest Athletic Conference'),
  ('University of Findlay', 'Findlay', 'OH', 'D2', 'Great Midwest Athletic Conference'),
  ('Walsh University', 'North Canton', 'OH', 'D2', 'Great Midwest Athletic Conference'),
  ('Central Washington University', 'Ellensburg', 'WA', 'D2', 'Great Northwest Athletic Conference'),
  ('Montana State University Billings', 'Billings', 'MT', 'D2', 'Great Northwest Athletic Conference'),
  ('Northwest Nazarene University', 'Nampa', 'ID', 'D2', 'Great Northwest Athletic Conference'),
  ('Saint Martin''s University', 'Lacey', 'WA', 'D2', 'Great Northwest Athletic Conference'),
  ('Western Oregon University', 'Monmouth', 'OR', 'D2', 'Great Northwest Athletic Conference'),
  ('Auburn University at Montgomery', 'Montgomery', 'AL', 'D2', 'Gulf South Conference'),
  ('Christian Brothers University', 'Memphis', 'TN', 'D2', 'Gulf South Conference'),
  ('Delta State University', 'Cleveland', 'MS', 'D2', 'Gulf South Conference'),
  ('Lee University', 'Cleveland', 'TN', 'D2', 'Gulf South Conference'),
  ('Mississippi College', 'Clinton', 'MS', 'D2', 'Gulf South Conference'),
  ('Trevecca Nazarene University', 'Nashville', 'TN', 'D2', 'Gulf South Conference'),
  ('Union University', 'Jackson', 'TN', 'D2', 'Gulf South Conference'),
  ('University of Alabama in Huntsville', 'Huntsville', 'AL', 'D2', 'Gulf South Conference'),
  ('University of Montevallo', 'Montevallo', 'AL', 'D2', 'Gulf South Conference'),
  ('University of West Alabama', 'Livingston', 'AL', 'D2', 'Gulf South Conference'),
  ('University of West Florida', 'Pensacola', 'FL', 'D2', 'Gulf South Conference'),
  ('Valdosta State University', 'Valdosta', 'GA', 'D2', 'Gulf South Conference'),
  ('Angelo State University', 'San Angelo', 'TX', 'D2', 'Lone Star Conference'),
  ('Cameron University', 'Lawton', 'OK', 'D2', 'Lone Star Conference'),
  ('Eastern New Mexico University', 'Portales', 'NM', 'D2', 'Lone Star Conference'),
  ('Lubbock Christian University', 'Lubbock', 'TX', 'D2', 'Lone Star Conference'),
  ('Oklahoma Christian University', 'Edmond', 'OK', 'D2', 'Lone Star Conference'),
  ('St. Edward''s University', 'Austin', 'TX', 'D2', 'Lone Star Conference'),
  ('St. Mary''s University', 'San Antonio', 'TX', 'D2', 'Lone Star Conference'),
  ('Sul Ross State University', 'Alpine', 'TX', 'D2', 'Lone Star Conference'),
  ('Texas A&M International University', 'Laredo', 'TX', 'D2', 'Lone Star Conference'),
  ('Texas A&M University-Kingsville', 'Kingsville', 'TX', 'D2', 'Lone Star Conference'),
  ('The University of Texas Permian Basin', 'Odessa', 'TX', 'D2', 'Lone Star Conference'),
  ('The University of Texas at Dallas', 'Richardson', 'TX', 'D2', 'Lone Star Conference'),
  ('The University of Texas at Tyler', 'Tyler', 'TX', 'D2', 'Lone Star Conference'),
  ('West Texas A&M University', 'Canyon', 'TX', 'D2', 'Lone Star Conference'),
  ('Emporia State University', 'Emporia', 'KS', 'D2', 'Mid-America Intercollegiate Athletics Association'),
  ('Fort Hays State University', 'Hays', 'KS', 'D2', 'Mid-America Intercollegiate Athletics Association'),
  ('Missouri Southern State University', 'Joplin', 'MO', 'D2', 'Mid-America Intercollegiate Athletics Association'),
  ('Missouri Western State University', 'St. Joseph', 'MO', 'D2', 'Mid-America Intercollegiate Athletics Association'),
  ('Newman University', 'Wichita', 'KS', 'D2', 'Mid-America Intercollegiate Athletics Association'),
  ('Northeastern State University', 'Tahlequah', 'OK', 'D2', 'Mid-America Intercollegiate Athletics Association'),
  ('Northwest Missouri State University', 'Maryville', 'MO', 'D2', 'Mid-America Intercollegiate Athletics Association'),
  ('Pittsburg State University', 'Pittsburg', 'KS', 'D2', 'Mid-America Intercollegiate Athletics Association'),
  ('Rogers State University', 'Claremore', 'OK', 'D2', 'Mid-America Intercollegiate Athletics Association'),
  ('University of Arkansas - Fort Smith', 'Fort Smith', 'AR', 'D2', 'Mid-America Intercollegiate Athletics Association'),
  ('University of Central Missouri', 'Warrensburg', 'MO', 'D2', 'Mid-America Intercollegiate Athletics Association'),
  ('University of Central Oklahoma', 'Edmond', 'OK', 'D2', 'Mid-America Intercollegiate Athletics Association'),
  ('Washburn University', 'Topeka', 'KS', 'D2', 'Mid-America Intercollegiate Athletics Association'),
  ('Concord University', 'Athens', 'WV', 'D2', 'Mountain East Conference'),
  ('Davis & Elkins College', 'Elkins', 'WV', 'D2', 'Mountain East Conference'),
  ('Fairmont State University', 'Fairmont', 'WV', 'D2', 'Mountain East Conference'),
  ('Frostburg State University', 'Frostburg', 'MD', 'D2', 'Mountain East Conference'),
  ('Glenville State University', 'Glenville', 'WV', 'D2', 'Mountain East Conference'),
  ('Point Park University', 'Pittsburgh', 'PA', 'D2', 'Mountain East Conference'),
  ('Shawnee State University', 'Portsmouth', 'OH', 'D2', 'Mountain East Conference'),
  ('University of Charleston', 'Charleston', 'WV', 'D2', 'Mountain East Conference'),
  ('West Liberty University', 'West Liberty', 'WV', 'D2', 'Mountain East Conference'),
  ('West Virginia State University', 'Institute', 'WV', 'D2', 'Mountain East Conference'),
  ('West Virginia Wesleyan College', 'Buckhannon', 'WV', 'D2', 'Mountain East Conference'),
  ('Wheeling University', 'Wheeling', 'WV', 'D2', 'Mountain East Conference'),
  ('Adelphi University', 'Garden City', 'NY', 'D2', 'Northeast-10 Conference'),
  ('American International College', 'Springfield', 'MA', 'D2', 'Northeast-10 Conference'),
  ('Assumption University', 'Worcester', 'MA', 'D2', 'Northeast-10 Conference'),
  ('Bentley University', 'Waltham', 'MA', 'D2', 'Northeast-10 Conference'),
  ('Franklin Pierce University', 'Rindge', 'NH', 'D2', 'Northeast-10 Conference'),
  ('Pace University', 'Pleasantville', 'NY', 'D2', 'Northeast-10 Conference'),
  ('Saint Anselm College', 'Goffstown', 'NH', 'D2', 'Northeast-10 Conference'),
  ('Saint Michael''s College', 'Colchester', 'VT', 'D2', 'Northeast-10 Conference'),
  ('Southern Connecticut State University', 'New Haven', 'CT', 'D2', 'Northeast-10 Conference'),
  ('Southern New Hampshire University', 'Manchester', 'NH', 'D2', 'Northeast-10 Conference'),
  ('Augustana University', 'Sioux Falls', 'SD', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('Bemidji State University', 'Bemidji', 'MN', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('Concordia University, St. Paul', 'Saint Paul', 'MN', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('Minnesota State University, Mankato', 'Mankato', 'MN', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('Minot State University', 'Minot', 'ND', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('Northern State University', 'Aberdeen', 'SD', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('Southwest Minnesota State University', 'Marshall', 'MN', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('St. Cloud State University', 'St. Cloud', 'MN', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('University of Jamestown', 'Jamestown', 'ND', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('University of Mary', 'Bismarck', 'ND', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('University of Minnesota Crookston', 'Crookston', 'MN', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('University of Minnesota Duluth', 'Duluth', 'MN', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('University of Sioux Falls', 'Sioux Falls', 'SD', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('Wayne State College', 'Wayne', 'NE', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('Winona State University', 'Winona', 'MN', 'D2', 'Northern Sun Intercollegiate Conference'),
  ('Biola University', 'La Mirada', 'CA', 'D2', 'Pacific West Conference'),
  ('Chaminade University of Honolulu', 'Honolulu', 'HI', 'D2', 'Pacific West Conference'),
  ('Concordia University Irvine', 'Irvine', 'CA', 'D2', 'Pacific West Conference'),
  ('Hawaii Pacific University', 'Honolulu', 'HI', 'D2', 'Pacific West Conference'),
  ('Jessup University', 'Rocklin', 'CA', 'D2', 'Pacific West Conference'),
  ('Point Loma Nazarene University', 'San Diego', 'CA', 'D2', 'Pacific West Conference'),
  ('University of Hawaii at Hilo', 'Hilo', 'HI', 'D2', 'Pacific West Conference'),
  ('Vanguard University of Southern California', 'Costa Mesa', 'CA', 'D2', 'Pacific West Conference'),
  ('Westmont College', 'Santa Barbara', 'CA', 'D2', 'Pacific West Conference'),
  ('Augusta University', 'Augusta', 'GA', 'D2', 'Peach Belt Conference'),
  ('Claflin University', 'Orangeburg', 'SC', 'D2', 'Peach Belt Conference'),
  ('Columbus State University', 'Columbus', 'GA', 'D2', 'Peach Belt Conference'),
  ('Flagler College', 'St. Augustine', 'FL', 'D2', 'Peach Belt Conference'),
  ('Georgia College & State University', 'Milledgeville', 'GA', 'D2', 'Peach Belt Conference'),
  ('Georgia Southwestern State University', 'Americus', 'GA', 'D2', 'Peach Belt Conference'),
  ('Lander University', 'Greenwood', 'SC', 'D2', 'Peach Belt Conference'),
  ('Middle Georgia State University', 'Macon', 'GA', 'D2', 'Peach Belt Conference'),
  ('University of North Georgia', 'Dahlonega', 'GA', 'D2', 'Peach Belt Conference'),
  ('University of South Carolina Aiken', 'Aiken', 'SC', 'D2', 'Peach Belt Conference'),
  ('University of South Carolina Beaufort', 'Bluffton', 'SC', 'D2', 'Peach Belt Conference'),
  ('Commonwealth University - Bloomsburg', 'Bloomsburg', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Commonwealth University - Lock Haven', 'Lock Haven', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Commonwealth University - Mansfield', 'Mansfield', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('East Stroudsburg University', 'East Stroudsburg', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Gannon University', 'Erie', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Indiana University of Pennsylvania', 'Indiana', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Kutztown University', 'Kutztown', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Lackawanna College', 'Scranton', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Millersville University', 'Millersville', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Pennsylvania Western University - California', 'California', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Pennsylvania Western University - Clarion', 'Clarion', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Seton Hill University', 'Greensburg', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Shepherd University', 'Shepherdstown', 'WV', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Shippensburg University', 'Shippensburg', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Slippery Rock University', 'Slippery Rock', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('University of Pittsburgh at Johnstown', 'Johnstown', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('West Chester University', 'West Chester', 'PA', 'D2', 'Pennsylvania State Athletic Conference'),
  ('Adams State University', 'Alamosa', 'CO', 'D2', 'Rocky Mountain Athletic Conference'),
  ('Colorado Christian University', 'Lakewood', 'CO', 'D2', 'Rocky Mountain Athletic Conference'),
  ('Colorado Mesa University', 'Grand Junction', 'CO', 'D2', 'Rocky Mountain Athletic Conference'),
  ('Colorado School of Mines', 'Golden', 'CO', 'D2', 'Rocky Mountain Athletic Conference'),
  ('Colorado State University Pueblo', 'Pueblo', 'CO', 'D2', 'Rocky Mountain Athletic Conference'),
  ('Metropolitan State University of Denver', 'Denver', 'CO', 'D2', 'Rocky Mountain Athletic Conference'),
  ('New Mexico Highlands University', 'Las Vegas', 'NM', 'D2', 'Rocky Mountain Athletic Conference'),
  ('Regis University', 'Denver', 'CO', 'D2', 'Rocky Mountain Athletic Conference'),
  ('University of Colorado Colorado Springs', 'Colorado Springs', 'CO', 'D2', 'Rocky Mountain Athletic Conference'),
  ('Anderson University', 'Anderson', 'SC', 'D2', 'South Atlantic Conference'),
  ('Carson-Newman University', 'Jefferson City', 'TN', 'D2', 'South Atlantic Conference'),
  ('Catawba College', 'Salisbury', 'NC', 'D2', 'South Atlantic Conference'),
  ('Coker University', 'Hartsville', 'SC', 'D2', 'South Atlantic Conference'),
  ('Emory & Henry University', 'Emory', 'VA', 'D2', 'South Atlantic Conference'),
  ('Lenoir-Rhyne University', 'Hickory', 'NC', 'D2', 'South Atlantic Conference'),
  ('Lincoln Memorial University', 'Harrogate', 'TN', 'D2', 'South Atlantic Conference'),
  ('Mars Hill University', 'Mars Hill', 'NC', 'D2', 'South Atlantic Conference'),
  ('Newberry College', 'Newberry', 'SC', 'D2', 'South Atlantic Conference'),
  ('Tusculum University', 'Tusculum', 'TN', 'D2', 'South Atlantic Conference'),
  ('University of Virginia''s College at Wise', 'Wise', 'VA', 'D2', 'South Atlantic Conference'),
  ('Wingate University', 'Wingate', 'NC', 'D2', 'South Atlantic Conference'),
  ('Albany State University', 'Albany', 'GA', 'D2', 'Southern Intercollegiate Athletic Conference'),
  ('Benedict College', 'Columbia', 'SC', 'D2', 'Southern Intercollegiate Athletic Conference'),
  ('Clark Atlanta University', 'Atlanta', 'GA', 'D2', 'Southern Intercollegiate Athletic Conference'),
  ('Edward Waters University', 'Jacksonville', 'FL', 'D2', 'Southern Intercollegiate Athletic Conference'),
  ('Kentucky State University', 'Frankfort', 'KY', 'D2', 'Southern Intercollegiate Athletic Conference'),
  ('Lane College', 'Jackson', 'TN', 'D2', 'Southern Intercollegiate Athletic Conference'),
  ('LeMoyne-Owen College', 'Memphis', 'TN', 'D2', 'Southern Intercollegiate Athletic Conference'),
  ('Miles College', 'Fairfield', 'AL', 'D2', 'Southern Intercollegiate Athletic Conference'),
  ('Morehouse College', 'Atlanta', 'GA', 'D2', 'Southern Intercollegiate Athletic Conference'),
  ('Savannah State University', 'Savannah', 'GA', 'D2', 'Southern Intercollegiate Athletic Conference'),
  ('Spring Hill College', 'Mobile', 'AL', 'D2', 'Southern Intercollegiate Athletic Conference'),
  ('Tuskegee University', 'Tuskegee', 'AL', 'D2', 'Southern Intercollegiate Athletic Conference'),
  ('Barry University', 'Miami Shores', 'FL', 'D2', 'Sunshine State Conference'),
  ('Eckerd College', 'St. Petersburg', 'FL', 'D2', 'Sunshine State Conference'),
  ('Embry-Riddle Aeronautical University', 'Daytona Beach', 'FL', 'D2', 'Sunshine State Conference'),
  ('Florida Institute of Technology', 'Melbourne', 'FL', 'D2', 'Sunshine State Conference'),
  ('Florida Southern College', 'Lakeland', 'FL', 'D2', 'Sunshine State Conference'),
  ('Lynn University', 'Boca Raton', 'FL', 'D2', 'Sunshine State Conference'),
  ('Nova Southeastern University', 'Davie', 'FL', 'D2', 'Sunshine State Conference'),
  ('Palm Beach Atlantic University', 'West Palm Beach', 'FL', 'D2', 'Sunshine State Conference'),
  ('Rollins College', 'Winter Park', 'FL', 'D2', 'Sunshine State Conference'),
  ('Saint Leo University', 'St. Leo', 'FL', 'D2', 'Sunshine State Conference'),
  ('University of Tampa', 'Tampa', 'FL', 'D2', 'Sunshine State Conference'),
  ('Bluefield State University', 'Bluefield', 'WV', 'D2', 'Division II Independents'),
  ('Salem University', 'Salem', 'WV', 'D2', 'Division II Independents')
on conflict (name_key, state_key) do update set
  division = excluded.division,
  conference = excluded.conference,
  city = coalesce(excluded.city, public.schools.city);

insert into public.conferences (name, division) values
  ('California Collegiate Athletic Association', 'D2'),
  ('Central Atlantic Collegiate Conference', 'D2'),
  ('Conference Carolinas', 'D2'),
  ('Division II Independents', 'D2'),
  ('East Coast Conference', 'D2'),
  ('Great American Conference', 'D2'),
  ('Great Lakes Intercollegiate Athletic Conference', 'D2'),
  ('Great Lakes Valley Conference', 'D2'),
  ('Great Midwest Athletic Conference', 'D2'),
  ('Great Northwest Athletic Conference', 'D2'),
  ('Gulf South Conference', 'D2'),
  ('Lone Star Conference', 'D2'),
  ('Mid-America Intercollegiate Athletics Association', 'D2'),
  ('Mountain East Conference', 'D2'),
  ('Northeast-10 Conference', 'D2'),
  ('Northern Sun Intercollegiate Conference', 'D2'),
  ('Pacific West Conference', 'D2'),
  ('Peach Belt Conference', 'D2'),
  ('Pennsylvania State Athletic Conference', 'D2'),
  ('Rocky Mountain Athletic Conference', 'D2'),
  ('South Atlantic Conference', 'D2'),
  ('Southern Intercollegiate Athletic Conference', 'D2'),
  ('Sunshine State Conference', 'D2')
on conflict (name_key, division) do nothing;
