-- 0022_d3_programs.sql
-- Seed D3 baseball programs (2026-27) into the schools reference
-- table, tagged with level and conference, so a coach who picks their
-- school gets the level + conference pre-filled (editable). Idempotent.

alter table public.schools add column if not exists division text;
alter table public.schools add column if not exists conference text;

insert into public.schools (name, city, state, division, conference) values
  ('Carlow University', 'Pittsburgh', 'PA', 'D3', 'Allegheny Mountain Collegiate Conference'),
  ('Hilbert College', 'Hamburg', 'NY', 'D3', 'Allegheny Mountain Collegiate Conference'),
  ('La Roche University', 'Pittsburgh', 'PA', 'D3', 'Allegheny Mountain Collegiate Conference'),
  ('Mount Aloysius College', 'Cresson', 'PA', 'D3', 'Allegheny Mountain Collegiate Conference'),
  ('Penn State Altoona', 'Altoona', 'PA', 'D3', 'Allegheny Mountain Collegiate Conference'),
  ('Penn State Behrend', 'Erie', 'PA', 'D3', 'Allegheny Mountain Collegiate Conference'),
  ('University of Pittsburgh at Bradford', 'Bradford', 'PA', 'D3', 'Allegheny Mountain Collegiate Conference'),
  ('University of Pittsburgh at Greensburg', 'Greensburg', 'PA', 'D3', 'Allegheny Mountain Collegiate Conference'),
  ('Buena Vista University', 'Storm Lake', 'IA', 'D3', 'American Rivers Conference'),
  ('Central College', 'Pella', 'IA', 'D3', 'American Rivers Conference'),
  ('Coe College', 'Cedar Rapids', 'IA', 'D3', 'American Rivers Conference'),
  ('Loras College', 'Dubuque', 'IA', 'D3', 'American Rivers Conference'),
  ('Nebraska Wesleyan University', 'Lincoln', 'NE', 'D3', 'American Rivers Conference'),
  ('Simpson College', 'Indianola', 'IA', 'D3', 'American Rivers Conference'),
  ('University of Dubuque', 'Dubuque', 'IA', 'D3', 'American Rivers Conference'),
  ('Wartburg College', 'Waverly', 'IA', 'D3', 'American Rivers Conference'),
  ('East Texas Baptist University', 'Marshall', 'TX', 'D3', 'American Southwest Conference'),
  ('Hardin-Simmons University', 'Abilene', 'TX', 'D3', 'American Southwest Conference'),
  ('Howard Payne University', 'Brownwood', 'TX', 'D3', 'American Southwest Conference'),
  ('McMurry University', 'Abilene', 'TX', 'D3', 'American Southwest Conference'),
  ('Schreiner University', 'Kerrville', 'TX', 'D3', 'American Southwest Conference'),
  ('University of Mary Hardin-Baylor', 'Belton', 'TX', 'D3', 'American Southwest Conference'),
  ('Centenary University', 'Hackettstown', 'NJ', 'D3', 'Atlantic East Conference'),
  ('Gwynedd Mercy University', 'Gwynedd Valley', 'PA', 'D3', 'Atlantic East Conference'),
  ('Immaculata University', 'Immaculata', 'PA', 'D3', 'Atlantic East Conference'),
  ('Marymount University', 'Arlington', 'VA', 'D3', 'Atlantic East Conference'),
  ('Saint Elizabeth University', 'Morristown', 'NJ', 'D3', 'Atlantic East Conference'),
  ('Dickinson College', 'Carlisle', 'PA', 'D3', 'Centennial Conference'),
  ('Franklin & Marshall College', 'Lancaster', 'PA', 'D3', 'Centennial Conference'),
  ('Gettysburg College', 'Gettysburg', 'PA', 'D3', 'Centennial Conference'),
  ('Haverford College', 'Haverford', 'PA', 'D3', 'Centennial Conference'),
  ('Johns Hopkins University', 'Baltimore', 'MD', 'D3', 'Centennial Conference'),
  ('McDaniel College', 'Westminster', 'MD', 'D3', 'Centennial Conference'),
  ('Muhlenberg College', 'Allentown', 'PA', 'D3', 'Centennial Conference'),
  ('Swarthmore College', 'Swarthmore', 'PA', 'D3', 'Centennial Conference'),
  ('Ursinus College', 'Collegeville', 'PA', 'D3', 'Centennial Conference'),
  ('Washington College', 'Chestertown', 'MD', 'D3', 'Centennial Conference'),
  ('Baruch College', 'New York', 'NY', 'D3', 'City University of New York Athletic Conference'),
  ('City College of New York', 'New York', 'NY', 'D3', 'City University of New York Athletic Conference'),
  ('John Jay College of Criminal Justice', 'New York', 'NY', 'D3', 'City University of New York Athletic Conference'),
  ('Lehman College', 'Bronx', 'NY', 'D3', 'City University of New York Athletic Conference'),
  ('Christopher Newport University', 'Newport News', 'VA', 'D3', 'Coast to Coast Athletic Conference'),
  ('Johnson & Wales University Charlotte', 'Charlotte', 'NC', 'D3', 'Coast to Coast Athletic Conference'),
  ('Regent University', 'Virginia Beach', 'VA', 'D3', 'Coast to Coast Athletic Conference'),
  ('Salisbury University', 'Salisbury', 'MD', 'D3', 'Coast to Coast Athletic Conference'),
  ('University of Mary Washington', 'Fredericksburg', 'VA', 'D3', 'Coast to Coast Athletic Conference'),
  ('Augustana College', 'Rock Island', 'IL', 'D3', 'College Conference of Illinois and Wisconsin'),
  ('Carroll University', 'Waukesha', 'WI', 'D3', 'College Conference of Illinois and Wisconsin'),
  ('Carthage College', 'Kenosha', 'WI', 'D3', 'College Conference of Illinois and Wisconsin'),
  ('Elmhurst University', 'Elmhurst', 'IL', 'D3', 'College Conference of Illinois and Wisconsin'),
  ('Illinois Wesleyan University', 'Bloomington', 'IL', 'D3', 'College Conference of Illinois and Wisconsin'),
  ('Millikin University', 'Decatur', 'IL', 'D3', 'College Conference of Illinois and Wisconsin'),
  ('North Central College', 'Naperville', 'IL', 'D3', 'College Conference of Illinois and Wisconsin'),
  ('North Park University', 'Chicago', 'IL', 'D3', 'College Conference of Illinois and Wisconsin'),
  ('Wheaton College', 'Wheaton', 'IL', 'D3', 'College Conference of Illinois and Wisconsin'),
  ('Asbury University', 'Wilmore', 'KY', 'D3', 'Collegiate Conference of the South'),
  ('Belhaven University', 'Jackson', 'MS', 'D3', 'Collegiate Conference of the South'),
  ('Covenant College', 'Lookout Mountain', 'GA', 'D3', 'Collegiate Conference of the South'),
  ('Huntingdon College', 'Montgomery', 'AL', 'D3', 'Collegiate Conference of the South'),
  ('LaGrange College', 'LaGrange', 'GA', 'D3', 'Collegiate Conference of the South'),
  ('Piedmont University', 'Demorest', 'GA', 'D3', 'Collegiate Conference of the South'),
  ('Curry College', 'Milton', 'MA', 'D3', 'Conference of New England'),
  ('Endicott College', 'Beverly', 'MA', 'D3', 'Conference of New England'),
  ('Gordon College', 'Wenham', 'MA', 'D3', 'Conference of New England'),
  ('Johnson & Wales University', 'Providence', 'RI', 'D3', 'Conference of New England'),
  ('Nichols College', 'Dudley', 'MA', 'D3', 'Conference of New England'),
  ('Roger Williams University', 'Bristol', 'RI', 'D3', 'Conference of New England'),
  ('Suffolk University', 'Boston', 'MA', 'D3', 'Conference of New England'),
  ('University of Hartford', 'West Hartford', 'CT', 'D3', 'Conference of New England'),
  ('Wentworth Institute of Technology', 'Boston', 'MA', 'D3', 'Conference of New England'),
  ('Western New England University', 'Springfield', 'MA', 'D3', 'Conference of New England'),
  ('Alfred University', 'Alfred', 'NY', 'D3', 'Empire 8'),
  ('Elmira College', 'Elmira', 'NY', 'D3', 'Empire 8'),
  ('Houghton University', 'Houghton', 'NY', 'D3', 'Empire 8'),
  ('Keuka College', 'Keuka Park', 'NY', 'D3', 'Empire 8'),
  ('Russell Sage College', 'Troy', 'NY', 'D3', 'Empire 8'),
  ('SUNY Brockport', 'Brockport', 'NY', 'D3', 'Empire 8'),
  ('SUNY Polytechnic Institute', 'Utica', 'NY', 'D3', 'Empire 8'),
  ('St. John Fisher University', 'Rochester', 'NY', 'D3', 'Empire 8'),
  ('Utica University', 'Utica', 'NY', 'D3', 'Empire 8'),
  ('Albertus Magnus College', 'New Haven', 'CT', 'D3', 'Great Northeast Athletic Conference'),
  ('Colby-Sawyer College', 'New London', 'NH', 'D3', 'Great Northeast Athletic Conference'),
  ('Dean College', 'Franklin', 'MA', 'D3', 'Great Northeast Athletic Conference'),
  ('Elms College', 'Chicopee', 'MA', 'D3', 'Great Northeast Athletic Conference'),
  ('Lasell University', 'Newton', 'MA', 'D3', 'Great Northeast Athletic Conference'),
  ('Mitchell College', 'New London', 'CT', 'D3', 'Great Northeast Athletic Conference'),
  ('New England College', 'Henniker', 'NH', 'D3', 'Great Northeast Athletic Conference'),
  ('Norwich University', 'Northfield', 'VT', 'D3', 'Great Northeast Athletic Conference'),
  ('Rivier University', 'Nashua', 'NH', 'D3', 'Great Northeast Athletic Conference'),
  ('Saint Joseph''s College of Maine', 'Standish', 'ME', 'D3', 'Great Northeast Athletic Conference'),
  ('University of Saint Joseph', 'West Hartford', 'CT', 'D3', 'Great Northeast Athletic Conference'),
  ('Anderson University', 'Anderson', 'IN', 'D3', 'Heartland Collegiate Athletic Conference'),
  ('Berea College', 'Berea', 'KY', 'D3', 'Heartland Collegiate Athletic Conference'),
  ('Bluffton University', 'Bluffton', 'OH', 'D3', 'Heartland Collegiate Athletic Conference'),
  ('Earlham College', 'Richmond', 'IN', 'D3', 'Heartland Collegiate Athletic Conference'),
  ('Franklin College', 'Franklin', 'IN', 'D3', 'Heartland Collegiate Athletic Conference'),
  ('Hanover College', 'Hanover', 'IN', 'D3', 'Heartland Collegiate Athletic Conference'),
  ('Manchester University', 'North Manchester', 'IN', 'D3', 'Heartland Collegiate Athletic Conference'),
  ('Mount St. Joseph University', 'Cincinnati', 'OH', 'D3', 'Heartland Collegiate Athletic Conference'),
  ('Rose-Hulman Institute of Technology', 'Terre Haute', 'IN', 'D3', 'Heartland Collegiate Athletic Conference'),
  ('Transylvania University', 'Lexington', 'KY', 'D3', 'Heartland Collegiate Athletic Conference'),
  ('Catholic University of America', 'Washington', 'DC', 'D3', 'Landmark Conference'),
  ('Drew University', 'Madison', 'NJ', 'D3', 'Landmark Conference'),
  ('Elizabethtown College', 'Elizabethtown', 'PA', 'D3', 'Landmark Conference'),
  ('Juniata College', 'Huntingdon', 'PA', 'D3', 'Landmark Conference'),
  ('Lycoming College', 'Williamsport', 'PA', 'D3', 'Landmark Conference'),
  ('Moravian University', 'Bethlehem', 'PA', 'D3', 'Landmark Conference'),
  ('Susquehanna University', 'Selinsgrove', 'PA', 'D3', 'Landmark Conference'),
  ('University of Scranton', 'Scranton', 'PA', 'D3', 'Landmark Conference'),
  ('Wilkes University', 'Wilkes-Barre', 'PA', 'D3', 'Landmark Conference'),
  ('Bard College', 'Annandale-on-Hudson', 'NY', 'D3', 'Liberty League'),
  ('Clarkson University', 'Potsdam', 'NY', 'D3', 'Liberty League'),
  ('Hobart College', 'Geneva', 'NY', 'D3', 'Liberty League'),
  ('Ithaca College', 'Ithaca', 'NY', 'D3', 'Liberty League'),
  ('Rensselaer Polytechnic Institute', 'Troy', 'NY', 'D3', 'Liberty League'),
  ('Rochester Institute of Technology', 'Rochester', 'NY', 'D3', 'Liberty League'),
  ('Skidmore College', 'Saratoga Springs', 'NY', 'D3', 'Liberty League'),
  ('St. Lawrence University', 'Canton', 'NY', 'D3', 'Liberty League'),
  ('Union College', 'Schenectady', 'NY', 'D3', 'Liberty League'),
  ('University of Rochester', 'Rochester', 'NY', 'D3', 'Liberty League'),
  ('Vassar College', 'Poughkeepsie', 'NY', 'D3', 'Liberty League'),
  ('Eastern Connecticut State University', 'Willimantic', 'CT', 'D3', 'Little East Conference'),
  ('Keene State College', 'Keene', 'NH', 'D3', 'Little East Conference'),
  ('Plymouth State University', 'Plymouth', 'NH', 'D3', 'Little East Conference'),
  ('Rhode Island College', 'Providence', 'RI', 'D3', 'Little East Conference'),
  ('University of Massachusetts Boston', 'Boston', 'MA', 'D3', 'Little East Conference'),
  ('University of Massachusetts Dartmouth', 'North Dartmouth', 'MA', 'D3', 'Little East Conference'),
  ('University of Southern Maine', 'Gorham', 'ME', 'D3', 'Little East Conference'),
  ('Vermont State University-Castleton', 'Castleton', 'VT', 'D3', 'Little East Conference'),
  ('Western Connecticut State University', 'Danbury', 'CT', 'D3', 'Little East Conference'),
  ('Anna Maria College', 'Paxton', 'MA', 'D3', 'Massachusetts State Collegiate Athletic Conference'),
  ('Bridgewater State University', 'Bridgewater', 'MA', 'D3', 'Massachusetts State Collegiate Athletic Conference'),
  ('Fitchburg State University', 'Fitchburg', 'MA', 'D3', 'Massachusetts State Collegiate Athletic Conference'),
  ('Framingham State University', 'Framingham', 'MA', 'D3', 'Massachusetts State Collegiate Athletic Conference'),
  ('Massachusetts College of Liberal Arts', 'North Adams', 'MA', 'D3', 'Massachusetts State Collegiate Athletic Conference'),
  ('Massachusetts Maritime Academy', 'Buzzards Bay', 'MA', 'D3', 'Massachusetts State Collegiate Athletic Conference'),
  ('Salem State University', 'Salem', 'MA', 'D3', 'Massachusetts State Collegiate Athletic Conference'),
  ('Westfield State University', 'Westfield', 'MA', 'D3', 'Massachusetts State Collegiate Athletic Conference'),
  ('Worcester State University', 'Worcester', 'MA', 'D3', 'Massachusetts State Collegiate Athletic Conference'),
  ('Adrian College', 'Adrian', 'MI', 'D3', 'Michigan Intercollegiate Athletic Association'),
  ('Albion College', 'Albion', 'MI', 'D3', 'Michigan Intercollegiate Athletic Association'),
  ('Alma College', 'Alma', 'MI', 'D3', 'Michigan Intercollegiate Athletic Association'),
  ('Calvin University', 'Grand Rapids', 'MI', 'D3', 'Michigan Intercollegiate Athletic Association'),
  ('Hope College', 'Holland', 'MI', 'D3', 'Michigan Intercollegiate Athletic Association'),
  ('Kalamazoo College', 'Kalamazoo', 'MI', 'D3', 'Michigan Intercollegiate Athletic Association'),
  ('Trine University', 'Angola', 'IN', 'D3', 'Michigan Intercollegiate Athletic Association'),
  ('University of Olivet', 'Olivet', 'MI', 'D3', 'Michigan Intercollegiate Athletic Association'),
  ('Albright College', 'Reading', 'PA', 'D3', 'Middle Atlantic Conference - Commonwealth'),
  ('Alvernia University', 'Reading', 'PA', 'D3', 'Middle Atlantic Conference - Commonwealth'),
  ('Eastern University', 'St. Davids', 'PA', 'D3', 'Middle Atlantic Conference - Commonwealth'),
  ('Hood College', 'Frederick', 'MD', 'D3', 'Middle Atlantic Conference - Commonwealth'),
  ('Messiah University', 'Mechanicsburg', 'PA', 'D3', 'Middle Atlantic Conference - Commonwealth'),
  ('Neumann University', 'Aston', 'PA', 'D3', 'Middle Atlantic Conference - Commonwealth'),
  ('Stevenson University', 'Owings Mills', 'MD', 'D3', 'Middle Atlantic Conference - Commonwealth'),
  ('Widener University', 'Chester', 'PA', 'D3', 'Middle Atlantic Conference - Commonwealth'),
  ('York College of Pennsylvania', 'York', 'PA', 'D3', 'Middle Atlantic Conference - Commonwealth'),
  ('Arcadia University', 'Glenside', 'PA', 'D3', 'Middle Atlantic Conference - Freedom'),
  ('DeSales University', 'Center Valley', 'PA', 'D3', 'Middle Atlantic Conference - Freedom'),
  ('Delaware Valley University', 'Doylestown', 'PA', 'D3', 'Middle Atlantic Conference - Freedom'),
  ('Fairleigh Dickinson University-Florham', 'Madison', 'NJ', 'D3', 'Middle Atlantic Conference - Freedom'),
  ('King''s College', 'Wilkes-Barre', 'PA', 'D3', 'Middle Atlantic Conference - Freedom'),
  ('Lebanon Valley College', 'Annville', 'PA', 'D3', 'Middle Atlantic Conference - Freedom'),
  ('Marywood University', 'Scranton', 'PA', 'D3', 'Middle Atlantic Conference - Freedom'),
  ('Misericordia University', 'Dallas', 'PA', 'D3', 'Middle Atlantic Conference - Freedom'),
  ('Stevens Institute of Technology', 'Hoboken', 'NJ', 'D3', 'Middle Atlantic Conference - Freedom'),
  ('Beloit College', 'Beloit', 'WI', 'D3', 'Midwest Conference'),
  ('Cornell College', 'Mount Vernon', 'IA', 'D3', 'Midwest Conference'),
  ('Grinnell College', 'Grinnell', 'IA', 'D3', 'Midwest Conference'),
  ('Illinois College', 'Jacksonville', 'IL', 'D3', 'Midwest Conference'),
  ('Knox College', 'Galesburg', 'IL', 'D3', 'Midwest Conference'),
  ('Lawrence University', 'Appleton', 'WI', 'D3', 'Midwest Conference'),
  ('Luther College', 'Decorah', 'IA', 'D3', 'Midwest Conference'),
  ('Monmouth College', 'Monmouth', 'IL', 'D3', 'Midwest Conference'),
  ('Ripon College', 'Ripon', 'WI', 'D3', 'Midwest Conference'),
  ('Augsburg University', 'Minneapolis', 'MN', 'D3', 'Minnesota Intercollegiate Athletic Conference'),
  ('Bethel University', 'Arden Hills', 'MN', 'D3', 'Minnesota Intercollegiate Athletic Conference'),
  ('Carleton College', 'Northfield', 'MN', 'D3', 'Minnesota Intercollegiate Athletic Conference'),
  ('College of St. Scholastica', 'Duluth', 'MN', 'D3', 'Minnesota Intercollegiate Athletic Conference'),
  ('Concordia College', 'Moorhead', 'MN', 'D3', 'Minnesota Intercollegiate Athletic Conference'),
  ('Gustavus Adolphus College', 'St. Peter', 'MN', 'D3', 'Minnesota Intercollegiate Athletic Conference'),
  ('Hamline University', 'St. Paul', 'MN', 'D3', 'Minnesota Intercollegiate Athletic Conference'),
  ('Macalester College', 'St. Paul', 'MN', 'D3', 'Minnesota Intercollegiate Athletic Conference'),
  ('Saint John''s University', 'Collegeville', 'MN', 'D3', 'Minnesota Intercollegiate Athletic Conference'),
  ('Saint Mary''s University of Minnesota', 'Winona', 'MN', 'D3', 'Minnesota Intercollegiate Athletic Conference'),
  ('St. Olaf College', 'Northfield', 'MN', 'D3', 'Minnesota Intercollegiate Athletic Conference'),
  ('Amherst College', 'Amherst', 'MA', 'D3', 'New England Small College Athletic Conference'),
  ('Bates College', 'Lewiston', 'ME', 'D3', 'New England Small College Athletic Conference'),
  ('Bowdoin College', 'Brunswick', 'ME', 'D3', 'New England Small College Athletic Conference'),
  ('Colby College', 'Waterville', 'ME', 'D3', 'New England Small College Athletic Conference'),
  ('Hamilton College', 'Clinton', 'NY', 'D3', 'New England Small College Athletic Conference'),
  ('Middlebury College', 'Middlebury', 'VT', 'D3', 'New England Small College Athletic Conference'),
  ('Trinity College', 'Hartford', 'CT', 'D3', 'New England Small College Athletic Conference'),
  ('Tufts University', 'Medford', 'MA', 'D3', 'New England Small College Athletic Conference'),
  ('Wesleyan University', 'Middletown', 'CT', 'D3', 'New England Small College Athletic Conference'),
  ('Williams College', 'Williamstown', 'MA', 'D3', 'New England Small College Athletic Conference'),
  ('Babson College', 'Wellesley', 'MA', 'D3', 'New England Women''s and Men''s Athletic Conference'),
  ('Clark University', 'Worcester', 'MA', 'D3', 'New England Women''s and Men''s Athletic Conference'),
  ('Emerson College', 'Boston', 'MA', 'D3', 'New England Women''s and Men''s Athletic Conference'),
  ('Massachusetts Institute of Technology', 'Cambridge', 'MA', 'D3', 'New England Women''s and Men''s Athletic Conference'),
  ('Salve Regina University', 'Newport', 'RI', 'D3', 'New England Women''s and Men''s Athletic Conference'),
  ('Springfield College', 'Springfield', 'MA', 'D3', 'New England Women''s and Men''s Athletic Conference'),
  ('United States Coast Guard Academy', 'New London', 'CT', 'D3', 'New England Women''s and Men''s Athletic Conference'),
  ('Wheaton College (MA)', 'Norton', 'MA', 'D3', 'New England Women''s and Men''s Athletic Conference'),
  ('Worcester Polytechnic Institute', 'Worcester', 'MA', 'D3', 'New England Women''s and Men''s Athletic Conference'),
  ('Kean University', 'Union', 'NJ', 'D3', 'New Jersey Athletic Conference'),
  ('Montclair State University', 'Montclair', 'NJ', 'D3', 'New Jersey Athletic Conference'),
  ('Ramapo College', 'Mahwah', 'NJ', 'D3', 'New Jersey Athletic Conference'),
  ('Rowan University', 'Glassboro', 'NJ', 'D3', 'New Jersey Athletic Conference'),
  ('Rutgers University-Camden', 'Camden', 'NJ', 'D3', 'New Jersey Athletic Conference'),
  ('Rutgers University-Newark', 'Newark', 'NJ', 'D3', 'New Jersey Athletic Conference'),
  ('SUNY New Paltz', 'New Paltz', 'NY', 'D3', 'New Jersey Athletic Conference'),
  ('Stockton University', 'Galloway', 'NJ', 'D3', 'New Jersey Athletic Conference'),
  ('The College of New Jersey', 'Ewing', 'NJ', 'D3', 'New Jersey Athletic Conference'),
  ('William Paterson University', 'Wayne', 'NJ', 'D3', 'New Jersey Athletic Conference'),
  ('Husson University', 'Bangor', 'ME', 'D3', 'North Atlantic Conference'),
  ('Lesley University', 'Cambridge', 'MA', 'D3', 'North Atlantic Conference'),
  ('Thomas College', 'Waterville', 'ME', 'D3', 'North Atlantic Conference'),
  ('University of Maine at Farmington', 'Farmington', 'ME', 'D3', 'North Atlantic Conference'),
  ('University of Maine at Presque Isle', 'Presque Isle', 'ME', 'D3', 'North Atlantic Conference'),
  ('Vermont State University-Lyndon', 'Lyndonville', 'VT', 'D3', 'North Atlantic Conference'),
  ('College of Wooster', 'Wooster', 'OH', 'D3', 'North Coast Athletic Conference'),
  ('DePauw University', 'Greencastle', 'IN', 'D3', 'North Coast Athletic Conference'),
  ('Denison University', 'Granville', 'OH', 'D3', 'North Coast Athletic Conference'),
  ('John Carroll University', 'University Heights', 'OH', 'D3', 'North Coast Athletic Conference'),
  ('Kenyon College', 'Gambier', 'OH', 'D3', 'North Coast Athletic Conference'),
  ('Oberlin College', 'Oberlin', 'OH', 'D3', 'North Coast Athletic Conference'),
  ('Ohio Wesleyan University', 'Delaware', 'OH', 'D3', 'North Coast Athletic Conference'),
  ('Wabash College', 'Crawfordsville', 'IN', 'D3', 'North Coast Athletic Conference'),
  ('Wittenberg University', 'Springfield', 'OH', 'D3', 'North Coast Athletic Conference'),
  ('Aurora University', 'Aurora', 'IL', 'D3', 'Northern Athletics Collegiate Conference'),
  ('Benedictine University', 'Lisle', 'IL', 'D3', 'Northern Athletics Collegiate Conference'),
  ('Concordia University Chicago', 'River Forest', 'IL', 'D3', 'Northern Athletics Collegiate Conference'),
  ('Concordia University Wisconsin', 'Mequon', 'WI', 'D3', 'Northern Athletics Collegiate Conference'),
  ('Dominican University', 'River Forest', 'IL', 'D3', 'Northern Athletics Collegiate Conference'),
  ('Edgewood University', 'Madison', 'WI', 'D3', 'Northern Athletics Collegiate Conference'),
  ('Illinois Institute of Technology', 'Chicago', 'IL', 'D3', 'Northern Athletics Collegiate Conference'),
  ('Lakeland University', 'Plymouth', 'WI', 'D3', 'Northern Athletics Collegiate Conference'),
  ('Marian University', 'Fond du Lac', 'WI', 'D3', 'Northern Athletics Collegiate Conference'),
  ('Milwaukee School of Engineering', 'Milwaukee', 'WI', 'D3', 'Northern Athletics Collegiate Conference'),
  ('Rockford University', 'Rockford', 'IL', 'D3', 'Northern Athletics Collegiate Conference'),
  ('St. Norbert College', 'De Pere', 'WI', 'D3', 'Northern Athletics Collegiate Conference'),
  ('Wisconsin Lutheran College', 'Milwaukee', 'WI', 'D3', 'Northern Athletics Collegiate Conference'),
  ('George Fox University', 'Newberg', 'OR', 'D3', 'Northwest Conference'),
  ('Lewis & Clark College', 'Portland', 'OR', 'D3', 'Northwest Conference'),
  ('Linfield University', 'McMinnville', 'OR', 'D3', 'Northwest Conference'),
  ('Pacific Lutheran University', 'Tacoma', 'WA', 'D3', 'Northwest Conference'),
  ('Pacific University', 'Forest Grove', 'OR', 'D3', 'Northwest Conference'),
  ('University of Puget Sound', 'Tacoma', 'WA', 'D3', 'Northwest Conference'),
  ('Whitman College', 'Walla Walla', 'WA', 'D3', 'Northwest Conference'),
  ('Whitworth University', 'Spokane', 'WA', 'D3', 'Northwest Conference'),
  ('Willamette University', 'Salem', 'OR', 'D3', 'Northwest Conference'),
  ('Baldwin Wallace University', 'Berea', 'OH', 'D3', 'Ohio Athletic Conference'),
  ('Capital University', 'Columbus', 'OH', 'D3', 'Ohio Athletic Conference'),
  ('Heidelberg University', 'Tiffin', 'OH', 'D3', 'Ohio Athletic Conference'),
  ('Marietta College', 'Marietta', 'OH', 'D3', 'Ohio Athletic Conference'),
  ('Muskingum University', 'New Concord', 'OH', 'D3', 'Ohio Athletic Conference'),
  ('Ohio Northern University', 'Ada', 'OH', 'D3', 'Ohio Athletic Conference'),
  ('Otterbein University', 'Westerville', 'OH', 'D3', 'Ohio Athletic Conference'),
  ('University of Mount Union', 'Alliance', 'OH', 'D3', 'Ohio Athletic Conference'),
  ('Wilmington College', 'Wilmington', 'OH', 'D3', 'Ohio Athletic Conference'),
  ('Averett University', 'Danville', 'VA', 'D3', 'Old Dominion Athletic Conference'),
  ('Batten University', 'Virginia Beach', 'VA', 'D3', 'Old Dominion Athletic Conference'),
  ('Bridgewater College', 'Bridgewater', 'VA', 'D3', 'Old Dominion Athletic Conference'),
  ('Eastern Mennonite University', 'Harrisonburg', 'VA', 'D3', 'Old Dominion Athletic Conference'),
  ('Guilford College', 'Greensboro', 'NC', 'D3', 'Old Dominion Athletic Conference'),
  ('Hampden-Sydney College', 'Hampden Sydney', 'VA', 'D3', 'Old Dominion Athletic Conference'),
  ('Randolph-Macon College', 'Ashland', 'VA', 'D3', 'Old Dominion Athletic Conference'),
  ('Roanoke College', 'Salem', 'VA', 'D3', 'Old Dominion Athletic Conference'),
  ('Shenandoah University', 'Winchester', 'VA', 'D3', 'Old Dominion Athletic Conference'),
  ('University of Lynchburg', 'Lynchburg', 'VA', 'D3', 'Old Dominion Athletic Conference'),
  ('Washington and Lee University', 'Lexington', 'VA', 'D3', 'Old Dominion Athletic Conference'),
  ('Allegheny College', 'Meadville', 'PA', 'D3', 'Presidents'' Athletic Conference'),
  ('Bethany College', 'Bethany', 'WV', 'D3', 'Presidents'' Athletic Conference'),
  ('Chatham University', 'Pittsburgh', 'PA', 'D3', 'Presidents'' Athletic Conference'),
  ('Franciscan University of Steubenville', 'Steubenville', 'OH', 'D3', 'Presidents'' Athletic Conference'),
  ('Geneva College', 'Beaver Falls', 'PA', 'D3', 'Presidents'' Athletic Conference'),
  ('Grove City College', 'Grove City', 'PA', 'D3', 'Presidents'' Athletic Conference'),
  ('Hiram College', 'Hiram', 'OH', 'D3', 'Presidents'' Athletic Conference'),
  ('Saint Vincent College', 'Latrobe', 'PA', 'D3', 'Presidents'' Athletic Conference'),
  ('Thiel College', 'Greenville', 'PA', 'D3', 'Presidents'' Athletic Conference'),
  ('Washington & Jefferson College', 'Washington', 'PA', 'D3', 'Presidents'' Athletic Conference'),
  ('Waynesburg University', 'Waynesburg', 'PA', 'D3', 'Presidents'' Athletic Conference'),
  ('Westminster College (PA)', 'New Wilmington', 'PA', 'D3', 'Presidents'' Athletic Conference'),
  ('Farmingdale State College', 'Farmingdale', 'NY', 'D3', 'Skyline Conference'),
  ('Manhattanville University', 'Purchase', 'NY', 'D3', 'Skyline Conference'),
  ('Mount Saint Mary College', 'Newburgh', 'NY', 'D3', 'Skyline Conference'),
  ('Purchase College', 'Purchase', 'NY', 'D3', 'Skyline Conference'),
  ('SUNY Maritime College', 'Bronx', 'NY', 'D3', 'Skyline Conference'),
  ('SUNY Old Westbury', 'Old Westbury', 'NY', 'D3', 'Skyline Conference'),
  ('St. Joseph''s University (Brooklyn)', 'Brooklyn', 'NY', 'D3', 'Skyline Conference'),
  ('St. Joseph''s University (Long Island)', 'Patchogue', 'NY', 'D3', 'Skyline Conference'),
  ('United States Merchant Marine Academy', 'Kings Point', 'NY', 'D3', 'Skyline Conference'),
  ('University of Mount Saint Vincent', 'Bronx', 'NY', 'D3', 'Skyline Conference'),
  ('Yeshiva University', 'New York', 'NY', 'D3', 'Skyline Conference'),
  ('Berry College', 'Mount Berry', 'GA', 'D3', 'Southern Athletic Association'),
  ('Centre College', 'Danville', 'KY', 'D3', 'Southern Athletic Association'),
  ('Maryville College', 'Maryville', 'TN', 'D3', 'Southern Athletic Association'),
  ('Millsaps College', 'Jackson', 'MS', 'D3', 'Southern Athletic Association'),
  ('Oglethorpe University', 'Brookhaven', 'GA', 'D3', 'Southern Athletic Association'),
  ('Rhodes College', 'Memphis', 'TN', 'D3', 'Southern Athletic Association'),
  ('Southwestern University', 'Georgetown', 'TX', 'D3', 'Southern Athletic Association'),
  ('Trinity University', 'San Antonio', 'TX', 'D3', 'Southern Athletic Association'),
  ('University of the South (Sewanee)', 'Sewanee', 'TN', 'D3', 'Southern Athletic Association'),
  ('Azusa Pacific University', 'Azusa', 'CA', 'D3', 'Southern California Intercollegiate Athletic Conference'),
  ('California Institute of Technology', 'Pasadena', 'CA', 'D3', 'Southern California Intercollegiate Athletic Conference'),
  ('California Lutheran University', 'Thousand Oaks', 'CA', 'D3', 'Southern California Intercollegiate Athletic Conference'),
  ('Chapman University', 'Orange', 'CA', 'D3', 'Southern California Intercollegiate Athletic Conference'),
  ('Claremont-Mudd-Scripps', 'Claremont', 'CA', 'D3', 'Southern California Intercollegiate Athletic Conference'),
  ('Occidental College', 'Los Angeles', 'CA', 'D3', 'Southern California Intercollegiate Athletic Conference'),
  ('Pomona-Pitzer', 'Claremont', 'CA', 'D3', 'Southern California Intercollegiate Athletic Conference'),
  ('University of La Verne', 'La Verne', 'CA', 'D3', 'Southern California Intercollegiate Athletic Conference'),
  ('University of Redlands', 'Redlands', 'CA', 'D3', 'Southern California Intercollegiate Athletic Conference'),
  ('Whittier College', 'Whittier', 'CA', 'D3', 'Southern California Intercollegiate Athletic Conference'),
  ('Austin College', 'Sherman', 'TX', 'D3', 'Southern Collegiate Athletic Conference'),
  ('Centenary College of Louisiana', 'Shreveport', 'LA', 'D3', 'Southern Collegiate Athletic Conference'),
  ('Concordia University Texas', 'Austin', 'TX', 'D3', 'Southern Collegiate Athletic Conference'),
  ('Hendrix College', 'Conway', 'AR', 'D3', 'Southern Collegiate Athletic Conference'),
  ('LeTourneau University', 'Longview', 'TX', 'D3', 'Southern Collegiate Athletic Conference'),
  ('Texas Lutheran University', 'Seguin', 'TX', 'D3', 'Southern Collegiate Athletic Conference'),
  ('University of Dallas', 'Irving', 'TX', 'D3', 'Southern Collegiate Athletic Conference'),
  ('University of St. Thomas', 'Houston', 'TX', 'D3', 'Southern Collegiate Athletic Conference'),
  ('University of the Ozarks', 'Clarksville', 'AR', 'D3', 'Southern Collegiate Athletic Conference'),
  ('Blackburn College', 'Carlinville', 'IL', 'D3', 'St. Louis Intercollegiate Athletic Conference'),
  ('Eureka College', 'Eureka', 'IL', 'D3', 'St. Louis Intercollegiate Athletic Conference'),
  ('Greenville University', 'Greenville', 'IL', 'D3', 'St. Louis Intercollegiate Athletic Conference'),
  ('Lyon College', 'Batesville', 'AR', 'D3', 'St. Louis Intercollegiate Athletic Conference'),
  ('Mississippi University for Women', 'Columbus', 'MS', 'D3', 'St. Louis Intercollegiate Athletic Conference'),
  ('Principia College', 'Elsah', 'IL', 'D3', 'St. Louis Intercollegiate Athletic Conference'),
  ('Spalding University', 'Louisville', 'KY', 'D3', 'St. Louis Intercollegiate Athletic Conference'),
  ('Webster University', 'Webster Groves', 'MO', 'D3', 'St. Louis Intercollegiate Athletic Conference'),
  ('Westminster College (MO)', 'Fulton', 'MO', 'D3', 'St. Louis Intercollegiate Athletic Conference'),
  ('Alfred State College', 'Alfred', 'NY', 'D3', 'State University of New York Athletic Conference'),
  ('SUNY Canton', 'Canton', 'NY', 'D3', 'State University of New York Athletic Conference'),
  ('SUNY Cobleskill', 'Cobleskill', 'NY', 'D3', 'State University of New York Athletic Conference'),
  ('SUNY Cortland', 'Cortland', 'NY', 'D3', 'State University of New York Athletic Conference'),
  ('SUNY Fredonia', 'Fredonia', 'NY', 'D3', 'State University of New York Athletic Conference'),
  ('SUNY Oneonta', 'Oneonta', 'NY', 'D3', 'State University of New York Athletic Conference'),
  ('SUNY Oswego', 'Oswego', 'NY', 'D3', 'State University of New York Athletic Conference'),
  ('SUNY Plattsburgh', 'Plattsburgh', 'NY', 'D3', 'State University of New York Athletic Conference'),
  ('Brevard College', 'Brevard', 'NC', 'D3', 'USA South Athletic Conference'),
  ('Greensboro College', 'Greensboro', 'NC', 'D3', 'USA South Athletic Conference'),
  ('Mary Baldwin University', 'Staunton', 'VA', 'D3', 'USA South Athletic Conference'),
  ('Methodist University', 'Fayetteville', 'NC', 'D3', 'USA South Athletic Conference'),
  ('North Carolina Wesleyan University', 'Rocky Mount', 'NC', 'D3', 'USA South Athletic Conference'),
  ('Pfeiffer University', 'Misenheimer', 'NC', 'D3', 'USA South Athletic Conference'),
  ('Southern Virginia University', 'Buena Vista', 'VA', 'D3', 'USA South Athletic Conference'),
  ('William Peace University', 'Raleigh', 'NC', 'D3', 'USA South Athletic Conference'),
  ('Cairn University', 'Langhorne', 'PA', 'D3', 'United East Conference'),
  ('Keystone College', 'La Plume', 'PA', 'D3', 'United East Conference'),
  ('Lancaster Bible College', 'Lancaster', 'PA', 'D3', 'United East Conference'),
  ('Notre Dame of Maryland University', 'Baltimore', 'MD', 'D3', 'United East Conference'),
  ('Penn State Abington', 'Abington', 'PA', 'D3', 'United East Conference'),
  ('Penn State Berks', 'Reading', 'PA', 'D3', 'United East Conference'),
  ('Penn State Brandywine', 'Media', 'PA', 'D3', 'United East Conference'),
  ('Penn State Harrisburg', 'Middletown', 'PA', 'D3', 'United East Conference'),
  ('Pennsylvania College of Technology', 'Williamsport', 'PA', 'D3', 'United East Conference'),
  ('St. Mary''s College of Maryland', 'St. Mary''s City', 'MD', 'D3', 'United East Conference'),
  ('University of Valley Forge', 'Phoenixville', 'PA', 'D3', 'United East Conference'),
  ('Wilson College', 'Chambersburg', 'PA', 'D3', 'United East Conference'),
  ('Brandeis University', 'Waltham', 'MA', 'D3', 'University Athletic Association'),
  ('Case Western Reserve University', 'Cleveland', 'OH', 'D3', 'University Athletic Association'),
  ('Emory University', 'Atlanta', 'GA', 'D3', 'University Athletic Association'),
  ('New York University', 'New York', 'NY', 'D3', 'University Athletic Association'),
  ('University of Chicago', 'Chicago', 'IL', 'D3', 'University Athletic Association'),
  ('Washington University in St. Louis', 'St. Louis', 'MO', 'D3', 'University Athletic Association'),
  ('Bethany Lutheran College', 'Mankato', 'MN', 'D3', 'Upper Midwest Athletic Conference'),
  ('Crown College', 'St. Bonifacius', 'MN', 'D3', 'Upper Midwest Athletic Conference'),
  ('Martin Luther College', 'New Ulm', 'MN', 'D3', 'Upper Midwest Athletic Conference'),
  ('North Central University', 'Minneapolis', 'MN', 'D3', 'Upper Midwest Athletic Conference'),
  ('University of Minnesota Morris', 'Morris', 'MN', 'D3', 'Upper Midwest Athletic Conference'),
  ('University of Northwestern-St. Paul', 'St. Paul', 'MN', 'D3', 'Upper Midwest Athletic Conference'),
  ('University of Wisconsin-Superior', 'Superior', 'WI', 'D3', 'Upper Midwest Athletic Conference'),
  ('University of Wisconsin-Eau Claire', 'Eau Claire', 'WI', 'D3', 'Wisconsin Intercollegiate Athletic Conference'),
  ('University of Wisconsin-La Crosse', 'La Crosse', 'WI', 'D3', 'Wisconsin Intercollegiate Athletic Conference'),
  ('University of Wisconsin-Oshkosh', 'Oshkosh', 'WI', 'D3', 'Wisconsin Intercollegiate Athletic Conference'),
  ('University of Wisconsin-Platteville', 'Platteville', 'WI', 'D3', 'Wisconsin Intercollegiate Athletic Conference'),
  ('University of Wisconsin-River Falls', 'River Falls', 'WI', 'D3', 'Wisconsin Intercollegiate Athletic Conference'),
  ('University of Wisconsin-Stevens Point', 'Stevens Point', 'WI', 'D3', 'Wisconsin Intercollegiate Athletic Conference'),
  ('University of Wisconsin-Stout', 'Menomonie', 'WI', 'D3', 'Wisconsin Intercollegiate Athletic Conference'),
  ('University of Wisconsin-Whitewater', 'Whitewater', 'WI', 'D3', 'Wisconsin Intercollegiate Athletic Conference'),
  ('Maranatha Baptist University', 'Watertown', 'WI', 'D3', 'Division III Independents')
on conflict (name_key, state_key) do update set
  division = excluded.division,
  conference = excluded.conference,
  city = coalesce(excluded.city, public.schools.city);

insert into public.conferences (name, division) values
  ('Allegheny Mountain Collegiate Conference', 'D3'),
  ('American Rivers Conference', 'D3'),
  ('American Southwest Conference', 'D3'),
  ('Atlantic East Conference', 'D3'),
  ('Centennial Conference', 'D3'),
  ('City University of New York Athletic Conference', 'D3'),
  ('Coast to Coast Athletic Conference', 'D3'),
  ('College Conference of Illinois and Wisconsin', 'D3'),
  ('Collegiate Conference of the South', 'D3'),
  ('Conference of New England', 'D3'),
  ('Division III Independents', 'D3'),
  ('Empire 8', 'D3'),
  ('Great Northeast Athletic Conference', 'D3'),
  ('Heartland Collegiate Athletic Conference', 'D3'),
  ('Landmark Conference', 'D3'),
  ('Liberty League', 'D3'),
  ('Little East Conference', 'D3'),
  ('Massachusetts State Collegiate Athletic Conference', 'D3'),
  ('Michigan Intercollegiate Athletic Association', 'D3'),
  ('Middle Atlantic Conference - Commonwealth', 'D3'),
  ('Middle Atlantic Conference - Freedom', 'D3'),
  ('Midwest Conference', 'D3'),
  ('Minnesota Intercollegiate Athletic Conference', 'D3'),
  ('New England Small College Athletic Conference', 'D3'),
  ('New England Women''s and Men''s Athletic Conference', 'D3'),
  ('New Jersey Athletic Conference', 'D3'),
  ('North Atlantic Conference', 'D3'),
  ('North Coast Athletic Conference', 'D3'),
  ('Northern Athletics Collegiate Conference', 'D3'),
  ('Northwest Conference', 'D3'),
  ('Ohio Athletic Conference', 'D3'),
  ('Old Dominion Athletic Conference', 'D3'),
  ('Presidents'' Athletic Conference', 'D3'),
  ('Skyline Conference', 'D3'),
  ('Southern Athletic Association', 'D3'),
  ('Southern California Intercollegiate Athletic Conference', 'D3'),
  ('Southern Collegiate Athletic Conference', 'D3'),
  ('St. Louis Intercollegiate Athletic Conference', 'D3'),
  ('State University of New York Athletic Conference', 'D3'),
  ('USA South Athletic Conference', 'D3'),
  ('United East Conference', 'D3'),
  ('University Athletic Association', 'D3'),
  ('Upper Midwest Athletic Conference', 'D3'),
  ('Wisconsin Intercollegiate Athletic Conference', 'D3')
on conflict (name_key, division) do nothing;
