-- 0023_juco_programs.sql
-- Seed JUCO baseball programs (2026-27) into the schools reference table,
-- tagged level JUCO with their conference, so a coach who picks their school
-- gets the level + conference pre-filled (editable). Idempotent.

alter table public.schools add column if not exists division text;
alter table public.schools add column if not exists conference text;

insert into public.schools (name, city, state, division, conference) values
  ('Arizona Western College', 'Yuma', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('Central Arizona College', 'Coolidge', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('Chandler-Gilbert Community College', 'Chandler', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('Cochise College', 'Douglas', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('College of Southern Nevada', 'Las Vegas', 'NV', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('Community Christian College', 'Redlands', 'CA', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('Eastern Arizona College', 'Thatcher', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('GateWay Community College', 'Phoenix', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('Glendale Community College (AZ)', 'Glendale', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('Mesa Community College', 'Mesa', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('Paradise Valley Community College', 'Phoenix', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('Phoenix College', 'Phoenix', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('Pima Community College', 'Tucson', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('Scottsdale Community College', 'Scottsdale', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('South Mountain Community College', 'Phoenix', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('Yavapai College', 'Prescott', 'AZ', 'JUCO', 'Arizona Community College Athletic Conference'),
  ('Arkansas State University Mid-South', 'West Memphis', 'AR', 'JUCO', 'NJCAA Region 2'),
  ('Arkansas State University Three Rivers', 'Malvern', 'AR', 'JUCO', 'NJCAA Region 2'),
  ('Arkansas State University-Mountain Home', 'Mountain Home', 'AR', 'JUCO', 'NJCAA Region 2'),
  ('Carl Albert State College', 'Poteau', 'OK', 'JUCO', 'NJCAA Region 2'),
  ('Connors State College', 'Warner', 'OK', 'JUCO', 'NJCAA Region 2'),
  ('Eastern Oklahoma State College', 'Wilburton', 'OK', 'JUCO', 'NJCAA Region 2'),
  ('Murray State College', 'Tishomingo', 'OK', 'JUCO', 'NJCAA Region 2'),
  ('National Park College', 'Hot Springs', 'AR', 'JUCO', 'NJCAA Region 2'),
  ('North Arkansas College', 'Harrison', 'AR', 'JUCO', 'NJCAA Region 2'),
  ('Northeastern Oklahoma A&M College', 'Miami', 'OK', 'JUCO', 'NJCAA Region 2'),
  ('Northern Oklahoma College-Enid', 'Enid', 'OK', 'JUCO', 'NJCAA Region 2'),
  ('Northern Oklahoma College-Tonkawa', 'Tonkawa', 'OK', 'JUCO', 'NJCAA Region 2'),
  ('Redlands Community College', 'El Reno', 'OK', 'JUCO', 'NJCAA Region 2'),
  ('Rose State College', 'Midwest City', 'OK', 'JUCO', 'NJCAA Region 2'),
  ('Seminole State College', 'Seminole', 'OK', 'JUCO', 'NJCAA Region 2'),
  ('South Arkansas College', 'El Dorado', 'AR', 'JUCO', 'NJCAA Region 2'),
  ('Southeast Arkansas College', 'Pine Bluff', 'AR', 'JUCO', 'NJCAA Region 2'),
  ('Southern Arkansas University Tech', 'Camden', 'AR', 'JUCO', 'NJCAA Region 2'),
  ('University of Arkansas Rich Mountain', 'Mena', 'AR', 'JUCO', 'NJCAA Region 2'),
  ('Western Oklahoma State College', 'Altus', 'OK', 'JUCO', 'NJCAA Region 2'),
  ('Cayuga Community College', 'Auburn', 'NY', 'JUCO', 'Mid-State Athletic Conference'),
  ('Corning Community College', 'Corning', 'NY', 'JUCO', 'Mid-State Athletic Conference'),
  ('Finger Lakes Community College', 'Canandaigua', 'NY', 'JUCO', 'Mid-State Athletic Conference'),
  ('Jefferson Community College', 'Watertown', 'NY', 'JUCO', 'Mid-State Athletic Conference'),
  ('Onondaga Community College', 'Syracuse', 'NY', 'JUCO', 'Mid-State Athletic Conference'),
  ('SUNY Broome', 'Binghamton', 'NY', 'JUCO', 'Mid-State Athletic Conference'),
  ('Tompkins Cortland Community College', 'Dryden', 'NY', 'JUCO', 'Mid-State Athletic Conference'),
  ('Fulton-Montgomery Community College', 'Johnstown', 'NY', 'JUCO', 'Mountain Valley Collegiate Conference'),
  ('Herkimer County Community College', 'Herkimer', 'NY', 'JUCO', 'Mountain Valley Collegiate Conference'),
  ('Hudson Valley Community College', 'Troy', 'NY', 'JUCO', 'Mountain Valley Collegiate Conference'),
  ('Mohawk Valley Community College', 'Utica', 'NY', 'JUCO', 'Mountain Valley Collegiate Conference'),
  ('SUNY Adirondack', 'Queensbury', 'NY', 'JUCO', 'Mountain Valley Collegiate Conference'),
  ('Genesee Community College', 'Batavia', 'NY', 'JUCO', 'Western New York Athletic Conference'),
  ('Monroe Community College', 'Rochester', 'NY', 'JUCO', 'Western New York Athletic Conference'),
  ('SUNY Erie (Erie CC)', 'Buffalo', 'NY', 'JUCO', 'Western New York Athletic Conference'),
  ('SUNY Jamestown (Jamestown CC)', 'Jamestown', 'NY', 'JUCO', 'Western New York Athletic Conference'),
  ('SUNY Niagara (Niagara County CC)', 'Sanborn', 'NY', 'JUCO', 'Western New York Athletic Conference'),
  ('Black Hawk College', 'Moline', 'IL', 'JUCO', 'Arrowhead Conference'),
  ('Carl Sandburg College', 'Galesburg', 'IL', 'JUCO', 'Arrowhead Conference'),
  ('Highland Community College (IL)', 'Freeport', 'IL', 'JUCO', 'Arrowhead Conference'),
  ('Illinois Valley Community College', 'Oglesby', 'IL', 'JUCO', 'Arrowhead Conference'),
  ('Kishwaukee College', 'Malta', 'IL', 'JUCO', 'Arrowhead Conference'),
  ('Sauk Valley Community College', 'Dixon', 'IL', 'JUCO', 'Arrowhead Conference'),
  ('College of Lake County', 'Grayslake', 'IL', 'JUCO', 'Illinois Skyway Collegiate Conference'),
  ('Elgin Community College', 'Elgin', 'IL', 'JUCO', 'Illinois Skyway Collegiate Conference'),
  ('McHenry County College', 'Crystal Lake', 'IL', 'JUCO', 'Illinois Skyway Collegiate Conference'),
  ('Moraine Valley Community College', 'Palos Hills', 'IL', 'JUCO', 'Illinois Skyway Collegiate Conference'),
  ('Morton College', 'Cicero', 'IL', 'JUCO', 'Illinois Skyway Collegiate Conference'),
  ('Oakton College', 'Des Plaines', 'IL', 'JUCO', 'Illinois Skyway Collegiate Conference'),
  ('Prairie State College', 'Chicago Heights', 'IL', 'JUCO', 'Illinois Skyway Collegiate Conference'),
  ('Waubonsee Community College', 'Sugar Grove', 'IL', 'JUCO', 'Illinois Skyway Collegiate Conference'),
  ('College of DuPage', 'Glen Ellyn', 'IL', 'JUCO', 'North Central Community College Conference'),
  ('Harper College', 'Palatine', 'IL', 'JUCO', 'North Central Community College Conference'),
  ('Joliet Junior College', 'Joliet', 'IL', 'JUCO', 'North Central Community College Conference'),
  ('Madison Area Technical College (Madison College)', 'Madison', 'WI', 'JUCO', 'North Central Community College Conference'),
  ('Milwaukee Area Technical College', 'Milwaukee', 'WI', 'JUCO', 'North Central Community College Conference'),
  ('Bryant & Stratton College - Wisconsin', 'Wauwatosa', 'WI', 'JUCO', 'Region 4'),
  ('Kankakee Community College', 'Kankakee', 'IL', 'JUCO', 'Region 4'),
  ('Kennedy-King College', 'Chicago', 'IL', 'JUCO', 'Region 4'),
  ('Olive-Harvey College', 'Chicago', 'IL', 'JUCO', 'Region 4'),
  ('Rock Valley College', 'Rockford', 'IL', 'JUCO', 'Region 4'),
  ('South Suburban College', 'South Holland', 'IL', 'JUCO', 'Region 4'),
  ('Triton College', 'River Grove', 'IL', 'JUCO', 'Region 4'),
  ('Dallas College Brookhaven', 'Farmers Branch', 'TX', 'JUCO', 'NJCAA Region 5'),
  ('Dallas College Cedar Valley', 'Lancaster', 'TX', 'JUCO', 'NJCAA Region 5'),
  ('Dallas College Eastfield', 'Mesquite', 'TX', 'JUCO', 'NJCAA Region 5'),
  ('Dallas College Mountain View', 'Dallas', 'TX', 'JUCO', 'NJCAA Region 5'),
  ('Dallas College North Lake', 'Irving', 'TX', 'JUCO', 'NJCAA Region 5'),
  ('Dallas College Richland', 'Dallas', 'TX', 'JUCO', 'NJCAA Region 5'),
  ('Cisco College', 'Cisco', 'TX', 'JUCO', 'North Texas Junior College Athletic Conference'),
  ('Grayson College', 'Denison', 'TX', 'JUCO', 'North Texas Junior College Athletic Conference'),
  ('Hill College', 'Hillsboro', 'TX', 'JUCO', 'North Texas Junior College Athletic Conference'),
  ('McLennan Community College', 'Waco', 'TX', 'JUCO', 'North Texas Junior College Athletic Conference'),
  ('North Central Texas College', 'Gainesville', 'TX', 'JUCO', 'North Texas Junior College Athletic Conference'),
  ('Ranger College', 'Ranger', 'TX', 'JUCO', 'North Texas Junior College Athletic Conference'),
  ('Temple College', 'Temple', 'TX', 'JUCO', 'North Texas Junior College Athletic Conference'),
  ('Vernon College', 'Vernon', 'TX', 'JUCO', 'North Texas Junior College Athletic Conference'),
  ('Weatherford College', 'Weatherford', 'TX', 'JUCO', 'North Texas Junior College Athletic Conference'),
  ('Amarillo College', 'Amarillo', 'TX', 'JUCO', 'Western Junior College Athletic Conference'),
  ('Clarendon College', 'Clarendon', 'TX', 'JUCO', 'Western Junior College Athletic Conference'),
  ('El Paso Community College', 'El Paso', 'TX', 'JUCO', 'Western Junior College Athletic Conference'),
  ('Frank Phillips College', 'Borger', 'TX', 'JUCO', 'Western Junior College Athletic Conference'),
  ('Howard College', 'Big Spring', 'TX', 'JUCO', 'Western Junior College Athletic Conference'),
  ('Midland College', 'Midland', 'TX', 'JUCO', 'Western Junior College Athletic Conference'),
  ('New Mexico Junior College', 'Hobbs', 'NM', 'JUCO', 'Western Junior College Athletic Conference'),
  ('New Mexico Military Institute', 'Roswell', 'NM', 'JUCO', 'Western Junior College Athletic Conference'),
  ('Odessa College', 'Odessa', 'TX', 'JUCO', 'Western Junior College Athletic Conference'),
  ('Western Texas College', 'Snyder', 'TX', 'JUCO', 'Western Junior College Athletic Conference'),
  ('Allen Community College', 'Iola', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Barton Community College', 'Great Bend', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Butler Community College', 'El Dorado', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Cloud County Community College', 'Concordia', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Coffeyville Community College', 'Coffeyville', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Colby Community College', 'Colby', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Cowley College', 'Arkansas City', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Dodge City Community College', 'Dodge City', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Fort Scott Community College', 'Fort Scott', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Garden City Community College', 'Garden City', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Highland Community College (KS)', 'Highland', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Hutchinson Community College', 'Hutchinson', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Johnson County Community College', 'Overland Park', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Kansas City Kansas Community College', 'Kansas City', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Labette Community College', 'Parsons', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Neosho County Community College', 'Chanute', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Pratt Community College', 'Pratt', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Seward County Community College', 'Liberal', 'KS', 'JUCO', 'Kansas Jayhawk Community College Conference'),
  ('Chattanooga State Community College', 'Chattanooga', 'TN', 'JUCO', 'Tennessee Community College Athletic Association'),
  ('Cleveland State Community College', 'Cleveland', 'TN', 'JUCO', 'Tennessee Community College Athletic Association'),
  ('Columbia State Community College', 'Columbia', 'TN', 'JUCO', 'Tennessee Community College Athletic Association'),
  ('Dyersburg State Community College', 'Dyersburg', 'TN', 'JUCO', 'Tennessee Community College Athletic Association'),
  ('Jackson State Community College', 'Jackson', 'TN', 'JUCO', 'Tennessee Community College Athletic Association'),
  ('Motlow State Community College', 'Lynchburg', 'TN', 'JUCO', 'Tennessee Community College Athletic Association'),
  ('Pellissippi State Community College', 'Knoxville', 'TN', 'JUCO', 'Tennessee Community College Athletic Association'),
  ('Roane State Community College', 'Harriman', 'TN', 'JUCO', 'Tennessee Community College Athletic Association'),
  ('Southwest Tennessee Community College', 'Memphis', 'TN', 'JUCO', 'Tennessee Community College Athletic Association'),
  ('Volunteer State Community College', 'Gallatin', 'TN', 'JUCO', 'Tennessee Community College Athletic Association'),
  ('Walters State Community College', 'Morristown', 'TN', 'JUCO', 'Tennessee Community College Athletic Association'),
  ('College of Central Florida', 'Ocala', 'FL', 'JUCO', 'Florida State College Activities Association - Citrus Conference'),
  ('Daytona State College', 'Daytona Beach', 'FL', 'JUCO', 'Florida State College Activities Association - Citrus Conference'),
  ('Eastern Florida State College', 'Cocoa', 'FL', 'JUCO', 'Florida State College Activities Association - Citrus Conference'),
  ('Florida SouthWestern State College', 'Fort Myers', 'FL', 'JUCO', 'Florida State College Activities Association - Citrus Conference'),
  ('Hillsborough Community College', 'Tampa', 'FL', 'JUCO', 'Florida State College Activities Association - Citrus Conference'),
  ('Indian River State College', 'Fort Pierce', 'FL', 'JUCO', 'Florida State College Activities Association - Citrus Conference'),
  ('Miami Dade College', 'Miami', 'FL', 'JUCO', 'Florida State College Activities Association - Citrus Conference'),
  ('Polk State College', 'Winter Haven', 'FL', 'JUCO', 'Florida State College Activities Association - Citrus Conference'),
  ('Santa Fe College', 'Gainesville', 'FL', 'JUCO', 'Florida State College Activities Association - Citrus Conference'),
  ('Seminole State College of Florida', 'Sanford', 'FL', 'JUCO', 'Florida State College Activities Association - Citrus Conference'),
  ('St. Petersburg College', 'St. Petersburg', 'FL', 'JUCO', 'Florida State College Activities Association - Citrus Conference'),
  ('State College of Florida, Manatee-Sarasota', 'Bradenton', 'FL', 'JUCO', 'Florida State College Activities Association - Citrus Conference'),
  ('Chipola College', 'Marianna', 'FL', 'JUCO', 'Florida State College Activities Association - Panhandle Conference'),
  ('Gulf Coast State College', 'Panama City', 'FL', 'JUCO', 'Florida State College Activities Association - Panhandle Conference'),
  ('Northwest Florida State College', 'Niceville', 'FL', 'JUCO', 'Florida State College Activities Association - Panhandle Conference'),
  ('Pensacola State College', 'Pensacola', 'FL', 'JUCO', 'Florida State College Activities Association - Panhandle Conference'),
  ('Tallahassee State College', 'Tallahassee', 'FL', 'JUCO', 'Florida State College Activities Association - Panhandle Conference'),
  ('Florida State College at Jacksonville', 'Jacksonville', 'FL', 'JUCO', 'Florida State College Activities Association - Sun-Lakes Conference'),
  ('Lake-Sumter State College', 'Leesburg', 'FL', 'JUCO', 'Florida State College Activities Association - Sun-Lakes Conference'),
  ('Palm Beach State College', 'Lake Worth', 'FL', 'JUCO', 'Florida State College Activities Association - Sun-Lakes Conference'),
  ('Pasco-Hernando State College', 'New Port Richey', 'FL', 'JUCO', 'Florida State College Activities Association - Sun-Lakes Conference'),
  ('South Florida State College', 'Avon Park', 'FL', 'JUCO', 'Florida State College Activities Association - Sun-Lakes Conference'),
  ('St. Johns River State College', 'Palatka', 'FL', 'JUCO', 'Florida State College Activities Association - Sun-Lakes Conference'),
  ('Lamar Community College', 'Lamar', 'CO', 'JUCO', 'NJCAA Region 9'),
  ('Luna Community College', 'Las Vegas', 'NM', 'JUCO', 'NJCAA Region 9'),
  ('McCook Community College', 'McCook', 'NE', 'JUCO', 'NJCAA Region 9'),
  ('Northeastern Junior College', 'Sterling', 'CO', 'JUCO', 'NJCAA Region 9'),
  ('Otero College', 'La Junta', 'CO', 'JUCO', 'NJCAA Region 9'),
  ('Southeast Community College', 'Beatrice', 'NE', 'JUCO', 'NJCAA Region 9'),
  ('Trinidad State College', 'Trinidad', 'CO', 'JUCO', 'NJCAA Region 9'),
  ('Western Nebraska Community College', 'Scottsbluff', 'NE', 'JUCO', 'NJCAA Region 9'),
  ('Brunswick Community College', 'Bolivia', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Bryant & Stratton College (Virginia Beach)', 'Virginia Beach', 'VA', 'JUCO', 'NJCAA Region 10'),
  ('Caldwell Community College & Technical Institute', 'Hudson', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Carteret Community College', 'Morehead City', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Catawba Valley Community College', 'Hickory', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Cleveland Community College', 'Shelby', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Fayetteville Technical Community College', 'Fayetteville', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Florence-Darlington Technical College', 'Florence', 'SC', 'JUCO', 'NJCAA Region 10'),
  ('Gaston College', 'Dallas', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Guilford Technical Community College', 'Jamestown', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Lenoir Community College', 'Kinston', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Louisburg College', 'Louisburg', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Patrick & Henry Community College', 'Martinsville', 'VA', 'JUCO', 'NJCAA Region 10'),
  ('Paul D. Camp Community College', 'Franklin', 'VA', 'JUCO', 'NJCAA Region 10'),
  ('Pitt Community College', 'Winterville', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Richard Bland College', 'Petersburg', 'VA', 'JUCO', 'NJCAA Region 10'),
  ('Robeson Community College', 'Lumberton', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Rockingham Community College', 'Wentworth', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Southeastern Community College (NC)', 'Whiteville', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Southwest Virginia Community College', 'Richlands', 'VA', 'JUCO', 'NJCAA Region 10'),
  ('Surry Community College', 'Dobson', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('USC Lancaster', 'Lancaster', 'SC', 'JUCO', 'NJCAA Region 10'),
  ('USC Salkehatchie', 'Allendale', 'SC', 'JUCO', 'NJCAA Region 10'),
  ('USC Sumter', 'Sumter', 'SC', 'JUCO', 'NJCAA Region 10'),
  ('USC Union', 'Union', 'SC', 'JUCO', 'NJCAA Region 10'),
  ('Virginia Peninsula Community College', 'Hampton', 'VA', 'JUCO', 'NJCAA Region 10'),
  ('Wake Technical Community College', 'Raleigh', 'NC', 'JUCO', 'NJCAA Region 10'),
  ('Des Moines Area Community College', 'Ankeny', 'IA', 'JUCO', 'Iowa Community College Athletic Conference'),
  ('Ellsworth Community College', 'Iowa Falls', 'IA', 'JUCO', 'Iowa Community College Athletic Conference'),
  ('Indian Hills Community College', 'Ottumwa', 'IA', 'JUCO', 'Iowa Community College Athletic Conference'),
  ('Iowa Central Community College', 'Fort Dodge', 'IA', 'JUCO', 'Iowa Community College Athletic Conference'),
  ('Iowa Lakes Community College', 'Estherville', 'IA', 'JUCO', 'Iowa Community College Athletic Conference'),
  ('Iowa Western Community College', 'Council Bluffs', 'IA', 'JUCO', 'Iowa Community College Athletic Conference'),
  ('Kirkwood Community College', 'Cedar Rapids', 'IA', 'JUCO', 'Iowa Community College Athletic Conference'),
  ('Marshalltown Community College', 'Marshalltown', 'IA', 'JUCO', 'Iowa Community College Athletic Conference'),
  ('North Iowa Area Community College', 'Mason City', 'IA', 'JUCO', 'Iowa Community College Athletic Conference'),
  ('Northeast Community College', 'Norfolk', 'NE', 'JUCO', 'Iowa Community College Athletic Conference'),
  ('Northeast Iowa Community College', 'Calmar', 'IA', 'JUCO', 'Iowa Community College Athletic Conference'),
  ('Southeastern Community College (IA)', 'West Burlington', 'IA', 'JUCO', 'Iowa Community College Athletic Conference'),
  ('Southwestern Community College', 'Creston', 'IA', 'JUCO', 'Iowa Community College Athletic Conference'),
  ('Alpena Community College', 'Alpena', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Bay College', 'Escanaba', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Delta College', 'University Center', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Glen Oaks Community College', 'Centreville', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Grand Rapids Community College', 'Grand Rapids', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Henry Ford College', 'Dearborn', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Jackson College', 'Jackson', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Kalamazoo Valley Community College', 'Kalamazoo', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Kellogg Community College', 'Battle Creek', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Lake Michigan College', 'Benton Harbor', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Lansing Community College', 'Lansing', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Macomb Community College', 'Warren', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Marian University Ancilla College', 'Donaldson', 'IN', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Mid Michigan College', 'Harrison', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Mott Community College', 'Flint', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Muskegon Community College', 'Muskegon', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Schoolcraft College', 'Livonia', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('St. Clair County Community College', 'Port Huron', 'MI', 'JUCO', 'Michigan Community College Athletic Association'),
  ('Bryant & Stratton College - Ohio', 'Parma', 'OH', 'JUCO', 'Ohio Community College Athletic Conference'),
  ('Clark State College', 'Springfield', 'OH', 'JUCO', 'Ohio Community College Athletic Conference'),
  ('Cuyahoga Community College', 'Cleveland', 'OH', 'JUCO', 'Ohio Community College Athletic Conference'),
  ('Edison State Community College', 'Piqua', 'OH', 'JUCO', 'Ohio Community College Athletic Conference'),
  ('Hocking College', 'Nelsonville', 'OH', 'JUCO', 'Ohio Community College Athletic Conference'),
  ('Lakeland Community College', 'Kirtland', 'OH', 'JUCO', 'Ohio Community College Athletic Conference'),
  ('Lorain County Community College', 'Elyria', 'OH', 'JUCO', 'Ohio Community College Athletic Conference'),
  ('Owens Community College', 'Perrysburg', 'OH', 'JUCO', 'Ohio Community College Athletic Conference'),
  ('Terra State Community College', 'Fremont', 'OH', 'JUCO', 'Ohio Community College Athletic Conference'),
  ('Alexandria Technical & Community College', 'Alexandria', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Anoka-Ramsey Community College', 'Coon Rapids', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Central Lakes College', 'Brainerd', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Century College', 'White Bear Lake', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Minnesota North College - Hibbing', 'Hibbing', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Minnesota North College - Itasca', 'Grand Rapids', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Minnesota North College - Mesabi Range', 'Virginia', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Minnesota North College - Rainy River', 'International Falls', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Minnesota North College - Vermilion', 'Ely', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Minnesota State Community & Technical College', 'Fergus Falls', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Minnesota West Community & Technical College', 'Worthington', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Northland Community & Technical College', 'Thief River Falls', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Ridgewater College', 'Willmar', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Riverland Community College', 'Austin', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Rochester Community & Technical College', 'Rochester', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('St. Cloud Technical & Community College', 'St. Cloud', 'MN', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Western Technical College', 'La Crosse', 'WI', 'JUCO', 'Minnesota College Athletic Conference'),
  ('Dakota College at Bottineau', 'Bottineau', 'ND', 'JUCO', 'Mon-Dak Conference'),
  ('Dawson Community College', 'Glendive', 'MT', 'JUCO', 'Mon-Dak Conference'),
  ('Lake Region State College', 'Devils Lake', 'ND', 'JUCO', 'Mon-Dak Conference'),
  ('Miles Community College', 'Miles City', 'MT', 'JUCO', 'Mon-Dak Conference'),
  ('North Dakota State College of Science', 'Wahpeton', 'ND', 'JUCO', 'Mon-Dak Conference'),
  ('Williston State College', 'Williston', 'ND', 'JUCO', 'Mon-Dak Conference'),
  ('Dakota County Technical College', 'Rosemount', 'MN', 'JUCO', 'NJCAA Region 13'),
  ('Alvin Community College', 'Alvin', 'TX', 'JUCO', 'NJCAA Region 14'),
  ('Angelina College', 'Lufkin', 'TX', 'JUCO', 'NJCAA Region 14'),
  ('Blinn College', 'Brenham', 'TX', 'JUCO', 'NJCAA Region 14'),
  ('Bossier Parish Community College', 'Bossier City', 'LA', 'JUCO', 'NJCAA Region 14'),
  ('Coastal Bend College', 'Beeville', 'TX', 'JUCO', 'NJCAA Region 14'),
  ('Galveston College', 'Galveston', 'TX', 'JUCO', 'NJCAA Region 14'),
  ('Navarro College', 'Corsicana', 'TX', 'JUCO', 'NJCAA Region 14'),
  ('Northeast Texas Community College', 'Mount Pleasant', 'TX', 'JUCO', 'NJCAA Region 14'),
  ('Panola College', 'Carthage', 'TX', 'JUCO', 'NJCAA Region 14'),
  ('Paris Junior College', 'Paris', 'TX', 'JUCO', 'NJCAA Region 14'),
  ('San Jacinto College', 'Pasadena', 'TX', 'JUCO', 'NJCAA Region 14'),
  ('Tyler Junior College', 'Tyler', 'TX', 'JUCO', 'NJCAA Region 14'),
  ('Wharton County Junior College', 'Wharton', 'TX', 'JUCO', 'NJCAA Region 14'),
  ('Borough of Manhattan Community College', 'New York', 'NY', 'JUCO', 'Region 15'),
  ('Bronx Community College', 'Bronx', 'NY', 'JUCO', 'Region 15'),
  ('Dutchess Community College', 'Poughkeepsie', 'NY', 'JUCO', 'Region 15'),
  ('Monroe University', 'New Rochelle', 'NY', 'JUCO', 'Region 15'),
  ('Monroe University - Bronx', 'Bronx', 'NY', 'JUCO', 'Region 15'),
  ('Nassau Community College', 'Garden City', 'NY', 'JUCO', 'Region 15'),
  ('Queensborough Community College', 'Bayside', 'NY', 'JUCO', 'Region 15'),
  ('Rockland Community College', 'Suffern', 'NY', 'JUCO', 'Region 15'),
  ('SUNY Orange', 'Middletown', 'NY', 'JUCO', 'Region 15'),
  ('SUNY Ulster', 'Stone Ridge', 'NY', 'JUCO', 'Region 15'),
  ('Suffolk County Community College', 'Selden', 'NY', 'JUCO', 'Region 15'),
  ('Westchester Community College', 'Valhalla', 'NY', 'JUCO', 'Region 15'),
  ('Crowder College', 'Neosho', 'MO', 'JUCO', 'Missouri Community College Athletic Conference'),
  ('East Central College', 'Union', 'MO', 'JUCO', 'Missouri Community College Athletic Conference'),
  ('Jefferson College', 'Hillsboro', 'MO', 'JUCO', 'Missouri Community College Athletic Conference'),
  ('Metropolitan Community College', 'Kansas City', 'MO', 'JUCO', 'Missouri Community College Athletic Conference'),
  ('Mineral Area College', 'Park Hills', 'MO', 'JUCO', 'Missouri Community College Athletic Conference'),
  ('Missouri State University-West Plains', 'West Plains', 'MO', 'JUCO', 'Missouri Community College Athletic Conference'),
  ('Moberly Area Community College', 'Moberly', 'MO', 'JUCO', 'Missouri Community College Athletic Conference'),
  ('North Central Missouri College', 'Trenton', 'MO', 'JUCO', 'Missouri Community College Athletic Conference'),
  ('St. Charles Community College', 'Cottleville', 'MO', 'JUCO', 'Missouri Community College Athletic Conference'),
  ('St. Louis Community College', 'St. Louis', 'MO', 'JUCO', 'Missouri Community College Athletic Conference'),
  ('State Fair Community College', 'Sedalia', 'MO', 'JUCO', 'Missouri Community College Athletic Conference'),
  ('Three Rivers College', 'Poplar Bluff', 'MO', 'JUCO', 'Missouri Community College Athletic Conference'),
  ('Georgia Highlands College', 'Rome', 'GA', 'JUCO', 'Georgia Collegiate Athletic Association'),
  ('Gordon State College', 'Barnesville', 'GA', 'JUCO', 'Georgia Collegiate Athletic Association'),
  ('South Georgia State College', 'Douglas', 'GA', 'JUCO', 'Georgia Collegiate Athletic Association'),
  ('College of Southern Idaho', 'Twin Falls', 'ID', 'JUCO', 'Scenic West Athletic Conference'),
  ('Colorado Northwestern Community College', 'Rangely', 'CO', 'JUCO', 'Scenic West Athletic Conference'),
  ('Salt Lake Community College', 'Salt Lake City', 'UT', 'JUCO', 'Scenic West Athletic Conference'),
  ('Utah State University Eastern', 'Price', 'UT', 'JUCO', 'Scenic West Athletic Conference'),
  ('Delaware County Community College', 'Media', 'PA', 'JUCO', 'Eastern Pennsylvania Athletic Conference'),
  ('Montgomery County Community College', 'Blue Bell', 'PA', 'JUCO', 'Eastern Pennsylvania Athletic Conference'),
  ('Northampton Community College', 'Bethlehem', 'PA', 'JUCO', 'Eastern Pennsylvania Athletic Conference'),
  ('Atlantic Cape Community College', 'Mays Landing', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('Bergen Community College', 'Paramus', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('Brookdale Community College', 'Lincroft', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('Camden County College', 'Blackwood', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('County College of Morris', 'Randolph', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('Mercer County Community College', 'West Windsor', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('Middlesex College', 'Edison', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('Ocean County College', 'Toms River', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('Raritan Valley Community College', 'Branchburg', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('Rowan College of South Jersey-Cumberland', 'Vineland', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('Rowan College of South Jersey-Gloucester', 'Sewell', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('Salem Community College', 'Carneys Point', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('Sussex County Community College', 'Newton', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('Union College of Union County', 'Cranford', 'NJ', 'JUCO', 'Garden State Athletic Conference'),
  ('Delaware Technical Community College', 'Georgetown', 'DE', 'JUCO', 'NJCAA Region 19'),
  ('Allegany College of Maryland', 'Cumberland', 'MD', 'JUCO', 'Maryland JUCO'),
  ('Anne Arundel Community College', 'Arnold', 'MD', 'JUCO', 'Maryland JUCO'),
  ('CCBC Catonsville', 'Catonsville', 'MD', 'JUCO', 'Maryland JUCO'),
  ('CCBC Dundalk', 'Dundalk', 'MD', 'JUCO', 'Maryland JUCO'),
  ('CCBC Essex', 'Rosedale', 'MD', 'JUCO', 'Maryland JUCO'),
  ('Cecil College', 'North East', 'MD', 'JUCO', 'Maryland JUCO'),
  ('Chesapeake College', 'Wye Mills', 'MD', 'JUCO', 'Maryland JUCO'),
  ('College of Southern Maryland', 'La Plata', 'MD', 'JUCO', 'Maryland JUCO'),
  ('Frederick Community College', 'Frederick', 'MD', 'JUCO', 'Maryland JUCO'),
  ('Garrett College', 'McHenry', 'MD', 'JUCO', 'Maryland JUCO'),
  ('Hagerstown Community College', 'Hagerstown', 'MD', 'JUCO', 'Maryland JUCO'),
  ('Harford Community College', 'Bel Air', 'MD', 'JUCO', 'Maryland JUCO'),
  ('Montgomery College', 'Rockville', 'MD', 'JUCO', 'Maryland JUCO'),
  ('Prince George''s Community College', 'Largo', 'MD', 'JUCO', 'Maryland JUCO'),
  ('Community College of Allegheny County', 'Pittsburgh', 'PA', 'JUCO', 'NJCAA Region 20'),
  ('Potomac State College of WVU', 'Keyser', 'WV', 'JUCO', 'NJCAA Region 20'),
  ('Westmoreland County Community College', 'Youngwood', 'PA', 'JUCO', 'NJCAA Region 20'),
  ('Bunker Hill Community College', 'Boston', 'MA', 'JUCO', 'NJCAA Region 21'),
  ('Community College of Rhode Island', 'Warwick', 'RI', 'JUCO', 'NJCAA Region 21'),
  ('Holyoke Community College', 'Holyoke', 'MA', 'JUCO', 'NJCAA Region 21'),
  ('Massasoit Community College', 'Brockton', 'MA', 'JUCO', 'NJCAA Region 21'),
  ('Northern Essex Community College', 'Haverhill', 'MA', 'JUCO', 'NJCAA Region 21'),
  ('Quinsigamond Community College', 'Worcester', 'MA', 'JUCO', 'NJCAA Region 21'),
  ('Roxbury Community College', 'Boston', 'MA', 'JUCO', 'NJCAA Region 21'),
  ('UConn Avery Point', 'Groton', 'CT', 'JUCO', 'NJCAA Region 21'),
  ('Bevill State Community College', 'Jasper', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Bishop State Community College', 'Mobile', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Calhoun Community College', 'Tanner', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Central Alabama Community College', 'Alexander City', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Chattahoochee Valley Community College', 'Phenix City', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Coastal Alabama Community College - East', 'Brewton', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Coastal Alabama Community College - North', 'Brewton', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Coastal Alabama Community College - South', 'Bay Minette', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Enterprise State Community College', 'Enterprise', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Gadsden State Community College', 'Gadsden', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Lawson State Community College', 'Birmingham', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Lurleen B. Wallace Community College', 'Andalusia', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Marion Military Institute', 'Marion', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Northwest-Shoals Community College', 'Muscle Shoals', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Reid State Technical College', 'Evergreen', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Shelton State Community College', 'Tuscaloosa', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Snead State Community College', 'Boaz', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Southern Union State Community College', 'Wadley', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Wallace Community College - Dothan', 'Dothan', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Wallace Community College - Selma', 'Selma', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Wallace State Community College', 'Hanceville', 'AL', 'JUCO', 'Alabama Community College Conference'),
  ('Baton Rouge Community College', 'Baton Rouge', 'LA', 'JUCO', 'Louisiana Community College Athletic Conference'),
  ('Delgado Community College', 'New Orleans', 'LA', 'JUCO', 'Louisiana Community College Athletic Conference'),
  ('Louisiana State University at Eunice', 'Eunice', 'LA', 'JUCO', 'Louisiana Community College Athletic Conference'),
  ('Nunez Community College', 'Chalmette', 'LA', 'JUCO', 'Louisiana Community College Athletic Conference'),
  ('Coahoma Community College', 'Clarksdale', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('Copiah-Lincoln Community College', 'Wesson', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('East Central Community College', 'Decatur', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('East Mississippi Community College', 'Scooba', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('Hinds Community College', 'Raymond', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('Holmes Community College', 'Goodman', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('Itawamba Community College', 'Fulton', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('Jones College', 'Ellisville', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('Meridian Community College', 'Meridian', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('Mississippi Delta Community College', 'Moorhead', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('Mississippi Gulf Coast Community College', 'Perkinston', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('Northeast Mississippi Community College', 'Booneville', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('Northwest Mississippi Community College', 'Senatobia', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('Pearl River Community College', 'Poplarville', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('Southwest Mississippi Community College', 'Summit', 'MS', 'JUCO', 'Mississippi Association of Community Colleges Conference'),
  ('Frontier Community College', 'Fairfield', 'IL', 'JUCO', 'Great Rivers Athletic Conference'),
  ('John A. Logan College', 'Carterville', 'IL', 'JUCO', 'Great Rivers Athletic Conference'),
  ('Kaskaskia College', 'Centralia', 'IL', 'JUCO', 'Great Rivers Athletic Conference'),
  ('Lake Land College', 'Mattoon', 'IL', 'JUCO', 'Great Rivers Athletic Conference'),
  ('Lincoln Trail College', 'Robinson', 'IL', 'JUCO', 'Great Rivers Athletic Conference'),
  ('Olney Central College', 'Olney', 'IL', 'JUCO', 'Great Rivers Athletic Conference'),
  ('Rend Lake College', 'Ina', 'IL', 'JUCO', 'Great Rivers Athletic Conference'),
  ('Shawnee Community College', 'Ullin', 'IL', 'JUCO', 'Great Rivers Athletic Conference'),
  ('Southeastern Illinois College', 'Harrisburg', 'IL', 'JUCO', 'Great Rivers Athletic Conference'),
  ('Southwestern Illinois College', 'Belleville', 'IL', 'JUCO', 'Great Rivers Athletic Conference'),
  ('Wabash Valley College', 'Mount Carmel', 'IL', 'JUCO', 'Great Rivers Athletic Conference'),
  ('Danville Area Community College', 'Danville', 'IL', 'JUCO', 'Mid-West Athletic Conference'),
  ('Heartland Community College', 'Normal', 'IL', 'JUCO', 'Mid-West Athletic Conference'),
  ('Illinois Central College', 'East Peoria', 'IL', 'JUCO', 'Mid-West Athletic Conference'),
  ('John Wood Community College', 'Quincy', 'IL', 'JUCO', 'Mid-West Athletic Conference'),
  ('Lewis and Clark Community College', 'Godfrey', 'IL', 'JUCO', 'Mid-West Athletic Conference'),
  ('Lincoln Land Community College', 'Springfield', 'IL', 'JUCO', 'Mid-West Athletic Conference'),
  ('Parkland College', 'Champaign', 'IL', 'JUCO', 'Mid-West Athletic Conference'),
  ('Spoon River College', 'Canton', 'IL', 'JUCO', 'Mid-West Athletic Conference'),
  ('Vincennes University', 'Vincennes', 'IN', 'JUCO', 'Mid-West Athletic Conference'),
  ('College of Marin', 'Kentfield', 'CA', 'JUCO', 'Bay Valley Conference'),
  ('Contra Costa College', 'San Pablo', 'CA', 'JUCO', 'Bay Valley Conference'),
  ('Laney College', 'Oakland', 'CA', 'JUCO', 'Bay Valley Conference'),
  ('Los Medanos College', 'Pittsburg', 'CA', 'JUCO', 'Bay Valley Conference'),
  ('Mendocino College', 'Ukiah', 'CA', 'JUCO', 'Bay Valley Conference'),
  ('Napa Valley College', 'Napa', 'CA', 'JUCO', 'Bay Valley Conference'),
  ('Solano Community College', 'Fairfield', 'CA', 'JUCO', 'Bay Valley Conference'),
  ('Yuba College', 'Marysville', 'CA', 'JUCO', 'Bay Valley Conference'),
  ('American River College', 'Sacramento', 'CA', 'JUCO', 'Big 8 Conference'),
  ('Cosumnes River College', 'Sacramento', 'CA', 'JUCO', 'Big 8 Conference'),
  ('Diablo Valley College', 'Pleasant Hill', 'CA', 'JUCO', 'Big 8 Conference'),
  ('Folsom Lake College', 'Folsom', 'CA', 'JUCO', 'Big 8 Conference'),
  ('Modesto Junior College', 'Modesto', 'CA', 'JUCO', 'Big 8 Conference'),
  ('Sacramento City College', 'Sacramento', 'CA', 'JUCO', 'Big 8 Conference'),
  ('San Joaquin Delta College', 'Stockton', 'CA', 'JUCO', 'Big 8 Conference'),
  ('Santa Rosa Junior College', 'Santa Rosa', 'CA', 'JUCO', 'Big 8 Conference'),
  ('Sierra College', 'Rocklin', 'CA', 'JUCO', 'Big 8 Conference'),
  ('College of the Sequoias', 'Visalia', 'CA', 'JUCO', 'Central Valley Conference'),
  ('Fresno City College', 'Fresno', 'CA', 'JUCO', 'Central Valley Conference'),
  ('Merced College', 'Merced', 'CA', 'JUCO', 'Central Valley Conference'),
  ('Porterville College', 'Porterville', 'CA', 'JUCO', 'Central Valley Conference'),
  ('Reedley College', 'Reedley', 'CA', 'JUCO', 'Central Valley Conference'),
  ('Taft College', 'Taft', 'CA', 'JUCO', 'Central Valley Conference'),
  ('West Hills College Coalinga', 'Coalinga', 'CA', 'JUCO', 'Central Valley Conference'),
  ('Cañada College', 'Redwood City', 'CA', 'JUCO', 'Coast Conference - North'),
  ('Chabot College', 'Hayward', 'CA', 'JUCO', 'Coast Conference - North'),
  ('City College of San Francisco', 'San Francisco', 'CA', 'JUCO', 'Coast Conference - North'),
  ('College of San Mateo', 'San Mateo', 'CA', 'JUCO', 'Coast Conference - North'),
  ('De Anza College', 'Cupertino', 'CA', 'JUCO', 'Coast Conference - North'),
  ('Skyline College', 'San Bruno', 'CA', 'JUCO', 'Coast Conference - North'),
  ('Cabrillo College', 'Aptos', 'CA', 'JUCO', 'Coast Conference - South'),
  ('Gavilan College', 'Gilroy', 'CA', 'JUCO', 'Coast Conference - South'),
  ('Hartnell College', 'Salinas', 'CA', 'JUCO', 'Coast Conference - South'),
  ('Monterey Peninsula College', 'Monterey', 'CA', 'JUCO', 'Coast Conference - South'),
  ('Ohlone College', 'Fremont', 'CA', 'JUCO', 'Coast Conference - South'),
  ('West Valley College', 'Saratoga', 'CA', 'JUCO', 'Coast Conference - South'),
  ('Butte College', 'Oroville', 'CA', 'JUCO', 'Golden Valley Conference'),
  ('College of the Redwoods', 'Eureka', 'CA', 'JUCO', 'Golden Valley Conference'),
  ('College of the Siskiyous', 'Weed', 'CA', 'JUCO', 'Golden Valley Conference'),
  ('Feather River College', 'Quincy', 'CA', 'JUCO', 'Golden Valley Conference'),
  ('Lassen Community College', 'Susanville', 'CA', 'JUCO', 'Golden Valley Conference'),
  ('Shasta College', 'Redding', 'CA', 'JUCO', 'Golden Valley Conference'),
  ('Barstow Community College', 'Barstow', 'CA', 'JUCO', 'Inland Empire Athletic Conference'),
  ('Cerro Coso Community College', 'Ridgecrest', 'CA', 'JUCO', 'Inland Empire Athletic Conference'),
  ('Chaffey College', 'Rancho Cucamonga', 'CA', 'JUCO', 'Inland Empire Athletic Conference'),
  ('College of the Desert', 'Palm Desert', 'CA', 'JUCO', 'Inland Empire Athletic Conference'),
  ('Mt. San Jacinto College', 'San Jacinto', 'CA', 'JUCO', 'Inland Empire Athletic Conference'),
  ('San Bernardino Valley College', 'San Bernardino', 'CA', 'JUCO', 'Inland Empire Athletic Conference'),
  ('Victor Valley College', 'Victorville', 'CA', 'JUCO', 'Inland Empire Athletic Conference'),
  ('Cypress College', 'Cypress', 'CA', 'JUCO', 'Orange Empire Conference'),
  ('Fullerton College', 'Fullerton', 'CA', 'JUCO', 'Orange Empire Conference'),
  ('Golden West College', 'Huntington Beach', 'CA', 'JUCO', 'Orange Empire Conference'),
  ('Irvine Valley College', 'Irvine', 'CA', 'JUCO', 'Orange Empire Conference'),
  ('Orange Coast College', 'Costa Mesa', 'CA', 'JUCO', 'Orange Empire Conference'),
  ('Riverside City College', 'Riverside', 'CA', 'JUCO', 'Orange Empire Conference'),
  ('Saddleback College', 'Mission Viejo', 'CA', 'JUCO', 'Orange Empire Conference'),
  ('Santa Ana College', 'Santa Ana', 'CA', 'JUCO', 'Orange Empire Conference'),
  ('Grossmont College', 'El Cajon', 'CA', 'JUCO', 'Pacific Coast Athletic Conference'),
  ('Imperial Valley College', 'Imperial', 'CA', 'JUCO', 'Pacific Coast Athletic Conference'),
  ('Palomar College', 'San Marcos', 'CA', 'JUCO', 'Pacific Coast Athletic Conference'),
  ('San Diego City College', 'San Diego', 'CA', 'JUCO', 'Pacific Coast Athletic Conference'),
  ('San Diego Mesa College', 'San Diego', 'CA', 'JUCO', 'Pacific Coast Athletic Conference'),
  ('Southwestern College', 'Chula Vista', 'CA', 'JUCO', 'Pacific Coast Athletic Conference'),
  ('Cerritos College', 'Norwalk', 'CA', 'JUCO', 'South Coast Conference'),
  ('Compton College', 'Compton', 'CA', 'JUCO', 'South Coast Conference'),
  ('East Los Angeles College', 'Monterey Park', 'CA', 'JUCO', 'South Coast Conference'),
  ('El Camino College', 'Torrance', 'CA', 'JUCO', 'South Coast Conference'),
  ('Los Angeles Harbor College', 'Wilmington', 'CA', 'JUCO', 'South Coast Conference'),
  ('Mt. San Antonio College', 'Walnut', 'CA', 'JUCO', 'South Coast Conference'),
  ('Pasadena City College', 'Pasadena', 'CA', 'JUCO', 'South Coast Conference'),
  ('Rio Hondo College', 'Whittier', 'CA', 'JUCO', 'South Coast Conference'),
  ('Allan Hancock College', 'Santa Maria', 'CA', 'JUCO', 'Western State Conference - North'),
  ('Cuesta College', 'San Luis Obispo', 'CA', 'JUCO', 'Western State Conference - North'),
  ('Los Angeles Pierce College', 'Woodland Hills', 'CA', 'JUCO', 'Western State Conference - North'),
  ('Moorpark College', 'Moorpark', 'CA', 'JUCO', 'Western State Conference - North'),
  ('Oxnard College', 'Oxnard', 'CA', 'JUCO', 'Western State Conference - North'),
  ('Santa Barbara City College', 'Santa Barbara', 'CA', 'JUCO', 'Western State Conference - North'),
  ('Ventura College', 'Ventura', 'CA', 'JUCO', 'Western State Conference - North'),
  ('Antelope Valley College', 'Lancaster', 'CA', 'JUCO', 'Western State Conference - South'),
  ('Bakersfield College', 'Bakersfield', 'CA', 'JUCO', 'Western State Conference - South'),
  ('Citrus College', 'Glendora', 'CA', 'JUCO', 'Western State Conference - South'),
  ('College of the Canyons', 'Santa Clarita', 'CA', 'JUCO', 'Western State Conference - South'),
  ('Glendale Community College (CA)', 'Glendale', 'CA', 'JUCO', 'Western State Conference - South'),
  ('Los Angeles Mission College', 'Sylmar', 'CA', 'JUCO', 'Western State Conference - South'),
  ('Los Angeles Valley College', 'Valley Glen', 'CA', 'JUCO', 'Western State Conference - South'),
  ('West Los Angeles College', 'Culver City', 'CA', 'JUCO', 'Western State Conference - South'),
  ('Big Bend Community College', 'Moses Lake', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Blue Mountain Community College', 'Pendleton', 'OR', 'JUCO', 'Northwest Athletic Conference'),
  ('Columbia Basin College', 'Pasco', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Community Colleges of Spokane', 'Spokane', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Treasure Valley Community College', 'Ontario', 'OR', 'JUCO', 'Northwest Athletic Conference'),
  ('Walla Walla Community College', 'Walla Walla', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Wenatchee Valley College', 'Wenatchee', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Yakima Valley College', 'Yakima', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Bellevue College', 'Bellevue', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Douglas College', 'New Westminster', 'BC', 'JUCO', 'Northwest Athletic Conference'),
  ('Edmonds College', 'Lynnwood', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Everett Community College', 'Everett', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Shoreline Community College', 'Shoreline', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Skagit Valley College', 'Mount Vernon', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Chemeketa Community College', 'Salem', 'OR', 'JUCO', 'Northwest Athletic Conference'),
  ('Clackamas Community College', 'Oregon City', 'OR', 'JUCO', 'Northwest Athletic Conference'),
  ('Lane Community College', 'Eugene', 'OR', 'JUCO', 'Northwest Athletic Conference'),
  ('Linn-Benton Community College', 'Albany', 'OR', 'JUCO', 'Northwest Athletic Conference'),
  ('Mt. Hood Community College', 'Gresham', 'OR', 'JUCO', 'Northwest Athletic Conference'),
  ('Southwestern Oregon Community College', 'Coos Bay', 'OR', 'JUCO', 'Northwest Athletic Conference'),
  ('Umpqua Community College', 'Roseburg', 'OR', 'JUCO', 'Northwest Athletic Conference'),
  ('Centralia College', 'Centralia', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Clark College', 'Vancouver', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Grays Harbor College', 'Aberdeen', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Lower Columbia College', 'Longview', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Olympic College', 'Bremerton', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Pierce College', 'Puyallup', 'WA', 'JUCO', 'Northwest Athletic Conference'),
  ('Tacoma Community College', 'Tacoma', 'WA', 'JUCO', 'Northwest Athletic Conference')
on conflict (name_key, state_key) do update set
  division = excluded.division,
  conference = excluded.conference,
  city = coalesce(excluded.city, public.schools.city);

insert into public.conferences (name, division) values
  ('Alabama Community College Conference', 'JUCO'),
  ('Arizona Community College Athletic Conference', 'JUCO'),
  ('Arrowhead Conference', 'JUCO'),
  ('Bay Valley Conference', 'JUCO'),
  ('Big 8 Conference', 'JUCO'),
  ('Central Valley Conference', 'JUCO'),
  ('Coast Conference - North', 'JUCO'),
  ('Coast Conference - South', 'JUCO'),
  ('Eastern Pennsylvania Athletic Conference', 'JUCO'),
  ('Florida State College Activities Association - Citrus Conference', 'JUCO'),
  ('Florida State College Activities Association - Panhandle Conference', 'JUCO'),
  ('Florida State College Activities Association - Sun-Lakes Conference', 'JUCO'),
  ('Garden State Athletic Conference', 'JUCO'),
  ('Georgia Collegiate Athletic Association', 'JUCO'),
  ('Golden Valley Conference', 'JUCO'),
  ('Great Rivers Athletic Conference', 'JUCO'),
  ('Illinois Skyway Collegiate Conference', 'JUCO'),
  ('Inland Empire Athletic Conference', 'JUCO'),
  ('Iowa Community College Athletic Conference', 'JUCO'),
  ('Kansas Jayhawk Community College Conference', 'JUCO'),
  ('Louisiana Community College Athletic Conference', 'JUCO'),
  ('Maryland JUCO', 'JUCO'),
  ('Michigan Community College Athletic Association', 'JUCO'),
  ('Mid-State Athletic Conference', 'JUCO'),
  ('Mid-West Athletic Conference', 'JUCO'),
  ('Minnesota College Athletic Conference', 'JUCO'),
  ('Mississippi Association of Community Colleges Conference', 'JUCO'),
  ('Missouri Community College Athletic Conference', 'JUCO'),
  ('Mon-Dak Conference', 'JUCO'),
  ('Mountain Valley Collegiate Conference', 'JUCO'),
  ('NJCAA Region 10', 'JUCO'),
  ('NJCAA Region 13', 'JUCO'),
  ('NJCAA Region 14', 'JUCO'),
  ('NJCAA Region 19', 'JUCO'),
  ('NJCAA Region 2', 'JUCO'),
  ('NJCAA Region 20', 'JUCO'),
  ('NJCAA Region 21', 'JUCO'),
  ('NJCAA Region 5', 'JUCO'),
  ('NJCAA Region 9', 'JUCO'),
  ('North Central Community College Conference', 'JUCO'),
  ('North Texas Junior College Athletic Conference', 'JUCO'),
  ('Northwest Athletic Conference', 'JUCO'),
  ('Ohio Community College Athletic Conference', 'JUCO'),
  ('Orange Empire Conference', 'JUCO'),
  ('Pacific Coast Athletic Conference', 'JUCO'),
  ('Region 15', 'JUCO'),
  ('Region 4', 'JUCO'),
  ('Scenic West Athletic Conference', 'JUCO'),
  ('South Coast Conference', 'JUCO'),
  ('Tennessee Community College Athletic Association', 'JUCO'),
  ('Western Junior College Athletic Conference', 'JUCO'),
  ('Western New York Athletic Conference', 'JUCO'),
  ('Western State Conference - North', 'JUCO'),
  ('Western State Conference - South', 'JUCO')
on conflict (name_key, division) do nothing;
